### ISSUE TITLE
[RAM Search] If you freeze all addresses in a new Search session, it will crash Bizhawk

### ISSUE THREAD

**Issue by tommai78101** [TASEmulators/BizHawk#1155]
Version: Bizhawk 2.2.2 Stable Release
OS: Windows 10 Pro Version 1709 Build 16299.248

Steps to reproduce:

1. Load up any GBA game (untested for any other games from different platforms)
3. Open RAM Search.
6. CTRL+A
7. Wait until it selects all of the addresses.
8. CTRL+F
9. Observe program crashes.

Expected results:

I should at least expect Bizhawk to respond to UI actions, like clicking on File > Open... in the RAM Search UI taskbar.

Actual results:

Bizhawk no longer responds, hard crash.

**Comment by YoshiRulz** [comment]
Could not reproduce on BizHawk 2.3 with the mGBA, Mupen64Plus, and QuickNes cores. Instead, the emulation acts like it's paused — except Mupen, on which both windows froze immediately. Attempting to un-freeze all the addresses caused both windows to freeze with mGBA and QuickNes. This is expected behaviour for freezing the whole memory. OS is Win10 Home 1709.

**Comment by Asnivor** [comment]
It looks like the whole RamSearch freezing part is actually using the cheat subsystem to freeze the addresses every frame (or maybe everytime said address is accessed - I dont know I havent looked properly). This introduces a massive amount of overhead when freezing an entire bus.

Unless the the cheat system is run on a different thread (not the UI thread) there will always be UI freezes in this kind of situation. 

Implementing this however is pretty much as far from trivial as you can get..

**Comment by YoshiRulz** [comment]
You could just add a confirmation box when the user when the user tries to freeze more than X addresses at once.
