### ISSUE TITLE
Command Line A/V Capture resolution

### ISSUE THREAD

**Issue by tevey** [TASEmulators/BizHawk#1226]
Hi,
I'm trying to dump mp4 video from the command line and everything works fine except that all videos have the resultion of the game. The Resize video option in File->Config and Record AVI/WAV seems to get lost as soon as i close the emulator.

**Comment by vadosnaprimer** [comment]
Why not resize the avi dump itself? That's how everyone is doing it.
http://tasvideos.org/EncodingGuide/CustomEncoding.html

Otherwise, pre-set specific resolution for the emulator itself and enable dumping with OSD, this captures the resulting client area instead of the game framebuffer.
Config - Display - Use custom size.
File - AVI - Capture OSD.

Just disable displaying the unwanted OSD elements.

**Comment by nattthebear** [comment]
>Why not resize the avi dump itself? That's how everyone is doing it.
That's TASVideos encoding advice and not really relevant anywhere else.  If he's dumping direct to mp4 and using command line dumping (where you can't know when to stop the encode for TASVideos rules) he clearly doesn't care about your secret club.

We should support this from the command line.
