### ISSUE TITLE
NesHawk FDS Zelda 1 doesn't save

### ISSUE THREAD

**Issue by HitakaPhoenix** [TASEmulators/BizHawk#1623]
For whatever reason, the FDS version of Zelda 1 doesn't retain save data, even though the save file appears in the SaveRAM folder. Other FDS games I tried, including Zelda 2 and Metroid, do save properly. One notable difference between those is that Zelda 1 saves on Side B, while Zelda 2 and Metroid save on Side A, so it may be an issue with games that save to Side B.

**Comment by alyosha-tas** [comment]
The problem here is that BizHawk checks the expected SRAM file size before loading it, but the FDS core hasn't built the entire diff state of the disk at reset (only one side) so saving on the B side gets truncated.

Other cores just get sent the complete SRAM file without checking and hope for the best, so that's what has to happen for FDS as well.
