### ISSUE TITLE
Callback to event.onmemorywrite sees the pre-write value at targeted address

### ISSUE THREAD

**Issue by aliblong** [TASEmulators/BizHawk#1732]
If I pass to `event.onmemorywrite` a callback that reads the value at that same address, the value it reads is the value *before* the write. This seems like it is not the desired behaviour.

[Video illustration](https://youtu.be/WXqsdK_AQ1E). The reason I'm not using the same memory domain for both `onmemorywrite` and `read_u32_be` is that I'm getting bugs (#1733 and #1734) when I specify non-default domains in either.

**Comment by vadosnaprimer** [comment]
Why is it not desired? All debuggers I've seen break _before_ execution. Maybe the problem is that in them you're meant to step into and see what happens, while in hawk you can only passively tracelog or run lua hooks. To know the value being written, you need to read the registers I guess.

**Comment by Zinfidel** [comment]
Perhaps a solution could involve mimicking the way .NET handles this kind of scenario within WinForms/WPF. Events frequently pass event arguments to the handling function that contain data about the values about to be written, so that the user can use them if needed. If the callbacks did this, they could fire before the write event as in a debugging breakpoint, but also give the user the new value.

This operates on the assumption that the cores will have a pretty good idea of the value that is about to be written to the memory address since they are aware of their instruction set and have to know to invoke callbacks when certain write commands are encountered.

Otherwise, the user has to get comfy with the instruction set of the core they are using, grab the memory at the PC, potentially figure out what kind of write instruction it is, and finally parse out the register.

**Comment by vadosnaprimer** [comment]
I think after hooks have been tweaked recently, it becomes possible to pass data along with them, it just takes someone to actually implement this in cores.

**Comment by YoshiRulz** [comment]
Reading memory within a memory callback is intended to give the "pre-write" value. With https://github.com/TASEmulators/BizHawk/commit/8385337e71144baccd22bb9e337fb2cf417d9de7, the value to be written is finally available to Lua callbacks as well:
```lua
event.onmemorywrite(function(addr, val, flags)
    print(memory.readbyte(addr)); -- current value
    print(val); -- value to be written
end);
```
