### ISSUE TITLE
CountPerOp=1 for Ocarina of Time May Be More Accurate

### ISSUE THREAD

**Issue by flagrama** [TASEmulators/BizHawk#1773]
This PR was recently created for Project64: https://github.com/project64/project64/pull/1692

I then attempted to test this on standalone mupen64plus. Setting CountPerOp=1 does appear to give the menu a more accurate timing with GLideN64 and glide64mk2. I was not able to get my standalone version of glide64 to work so couldn't test it there. The most noticeable to me was Rice. It still takes way too long, but the menu takes twice as long to open on CountPerOp=0 and CountPerOp=2 as it takes on CountPerOp=1

I think it at least requires further testing. If it is determined to be more accurate though it would be appreciated if it could be set somewhere for Ocarina of Time Randomizer roms.

**Comment by CasualPokePlayer** [comment]
It's definitely not "more accurate" here. That entire setting is a hack which makes every opcode take a set number of cycles. The reality is that is not how the N64 works, opcodes take a variable amount of timing depending on many factors. And of course different games don't get to choose the timing (any per game hack is not accurate). The setting exists because timing is so fubared some games might just crash with the default value.

Even so, our Mupen64Plus is so old it predates this setting existing, so we can't add it for us. If we were to add it, it'd just be something in the gamedb the community can manually add.
