### ISSUE TITLE
Paper Mario (N64) flickering

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASEmulators/BizHawk#186]
```
What steps will reproduce the problem?
1. Open a Paper Mario (USA) ROM
2. Play the game up to the opening
3.

What is the expected output? What do you see instead?
Expected: The game plays normally
What really happens: Every second frame is only a background

What version of the product are you using? On what operating system?
BizHawk 1.7.0 on Windows 8 (x86-64)

Please provide any additional information below.


```

Original issue reported on code.google.com by `tdbakst...@gmail.com` on 9 Jun 2014 at 11:49
- Merged into: #162

**Comment by getCursorsExe** [comment]
This garbage mess occurs because Paper Mario 64 actually wants to use the Frame Buffer Emulation, and when this is disabled, invaild frames are being rendered. You have to enable it to play the game normally, but this messes up savestates due to frame buffer being refreshed every time you load a savestate.

**Comment by zeromus** [comment]
Wait, why does "frame buffer being refreshed every time you load a savestate" present a problem?

**Comment by getCursorsExe** [comment]
Loading savestates makes everything disappear at some point except for backgroud. No idea why this occurs, perhaps the upstream has this too?
