### ISSUE TITLE
[IntelliHawk] List of games having bugs/crashing or require something as of Bizhawk Dev 2020-05-09

### ISSUE THREAD

**Issue by ghost** [TASEmulators/BizHawk#1992]
LASTEST UPDATE : June 28 2020

Here a list of every Intellivision games that are not working or have bugs/crashes or requires something that is not emulated yet. This list includes the original 119 games, the six Keyboard Component games, 4-Tris and official rerelease of game that were not released back then and cartridge homebrew

Games that crashes with the following error below
![spike volleyballcrash](https://user-images.githubusercontent.com/24578279/81488041-e1f1e280-9231-11ea-9486-400b3307bc34.PNG)

- [x] - Motocross (crashes after options selection)
- [x] - Spiker! Super Pro Volleyball (Crash immediately)
- [x] - BlowOut (Rerelease of Mattel's 1982 game) (Crashes after title screen)
- [x] - Scarfinger (Rerelease of Mattel's 1982 game) (Crashes after title screen)
- [x] - Deep Pockets-Super Pro Pool and Billiards (Unreleased game that was later released by Blue Sky Rangers in 2019) (Crash immediately)
- [x] - Hotel Bunny (Homebrew game released in 2017 in cartridge format) (Crash immediately)
- [x] - Minehunter (Homebrew from 2003) (Crash immediately)
- [x] - Copter Command (Homebrew game released in 2015 in cartridge format) (Crash immediately)
- [x] - Stonix (Homebrew game released in 2003 in cartridge format) (Crash immediately)
- [x] - Pumpkin Master (Homebrew game released in 2018 in cartridge format) (Crash immediately)
- [x] - Laser Sharks (Homebrew game released in 2017 in cartridge format) (Crash immediately)
- [x] - Missile Domination (Homebrew game released in 2016 in cartridge format) (Crash immediately)
- [x] - Sea Venture (Homebrew game released in 2018 in cartridge format) (Crash immediately)
- [x] - Secret Government Waffle Project, The (Homebrew game released in 2018 in cartridge format) (Very glitched title screen, crash as soon as a button is press)
- [x] - Ultimate Pong (Homebrew game released in 2016 in cartridge format) (Crash immediately)
- [x] - Moon Blast (Homebrew game released in 2017 in cartridge format) (Crash immediately)

Games that start with a blank screen
- [x] - Triple Challenge (a green rectangle surrounding the black appear after a few minute), orthewise, nothing happen and the game doesn't work
- [x] - Flappy Bird (Homebrew game made in cartridge in 2015)

Don't Work as intended
- [x] - Checkers (AI does not work)
- [x] - Reversi (AI does not work) 

Games with graphical glitches

- [x] - Slam Dunk Super Pro Basketball (Title screen glitches, but the game does play well)
- [x] - PBA Bowling (Extra glitched graphics on the left side of the bowler, before you throw your ball, but game work otherwise.)

~~Intellivoice enhanced game that does not emulate the voice itself~~
~~Entertainment Computer System~~
These peripherals are un-emulated, they are in a separate issue.

A big thank you for the Bizhawk team!

**Comment by Elohimuel** [comment]
Download the latest artifact, I presume Yoshi. That can be found on the TAS speed run video site as found in the resources or the index. Though the firmware files remain the same or detected but perhaps not known.

https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts
Though, I found a different link as there was a base branch.
The folder build cannot be found here but they say there were no conflicts as of the base.

2020-05-13-162535-#01089645cc7275e267cae27a12afa8a3a8fe83ec (main DEV) branch.
As it is being developed this minute the pulls.

Replace the appropriate firmware files as found on the internet archives but not developer-build. Please note, I am not supporting leakage of game spoilers but want to contribute what is found out about it. To others like you need a chance to build so here are some instructions.

For the firmware user hash is empty. It requires an emulator of some sort to be formatted,
then dump the firmware bin some how with a homebrew running the DSI set up as provided by Martin or Nathan a long time ago and not the revised setup which crashes. This will delete the card games, so make backup of those titles but will understand the firmware situation or reformat it to ones own user name.

Not sure if that helps with formatting the hash of the file though, so strictly this has to do with a common key issue as related to ones user hash after formatting and deleting the games on the actual DSI emulator or renaming nan.bin to firmware.bin. So because Nintendo requires certs some of the services you offer may or may not work - but because this is the developer device, it is associated to how the firm runs within the deploying system or main domain. So one would need a firmware dumper homebrew as associated.

That is strictly up to the Cloud providers of Enzu corporation about the link to other services. = As associated to Google, Apple, you name it though the system is developed. One can host their own service or with cartridges which one as yourself has or develops. As Nintendo would cut their services in 2020 or associated to Pokémon company, they have damaged the reputation of others to people cheated and at one point like me tested the databases around many regions. If one is a programmer that is different with what is done with the code and are held to higher standards. When the admin go rouge, that is questionable, as determined.

But strictly this is to help you and others develop. so here you go.
Advice has been offered. ^-^

**Comment by Glitcholog** [comment]
UPDATE : Added BlowOut in the list.

**Comment by YoshiRulz** [comment]
Checkers (`sha1:4FEF3342C0E7100113B4022E4395AD552FDDACF1`) and Reversi (`sha1:3EEA6F5C02942EB3AC96967E3B667911459D09F8`) are missing from the gamedb, and aren't emulated correctly when the default mapper 0 is used. Specifically the 1-player (vs. AI) modes don't work.

**Comment by Winslinator** [comment]
Please add Minehunter to the list of games with the same crash error posted. It is also a homebrew from 2003.

**Comment by alyosha-tas** [comment]
I updated this issue a bit. I updated a few things in the game db which made a few of these work correctly. I moved ECS to #1778 with intellivoice, as those aren't likely to be fixed soon.

Intellivision core has not aged well and probably should be replaced, but i'll see which of these I can fix with just DB updates.

**Comment by alyosha-tas** [comment]
most of these modern homebrews come in 'intellicart' format which happened to be broken in the core.

Having fixed this it seems all the ones I could find worked, so closing this. There could be some larger games using bankswitching + intellicart but I haven't found any, but they can be fixed if any pop up.

**Comment by YoshiRulz** [comment]
Atari's *Pac-Man* port (`SHA1:66DDC9C56EDEE06564C1252C7C6BC3123DA8C31D`/`MD5:34B9E686AEE6F418D431A2F9A5A5C0CB`) draws nothing for a bit, then draws garbage, then hits a `HLT` which throws an exception.

**Comment by alyosha-tas** [comment]
works fine for me in dev build.

**Comment by YoshiRulz** [comment]
My bad, I must have been using 2.7.
