### ISSUE TITLE
[TAStudio] Better labels for custom colors for colorblindness

### ISSUE THREAD

**Issue by Spikestuff** [TASEmulators/BizHawk#2119]
On TASVideos' Discord a member asked a question if it was possible for TAStudio to change colors for their colorblindness (deuteranopia).
This user was using Windows 10's color filters to help, but it's not as effective for them with the shade of colors Hawk uses.

Something similar to the _configure on screen messages_ window might be more than enough for this.

**Comment by YoshiRulz** [comment]
see also #1617; TAStudio highlights are the easiest colours to change

**Comment by RetroEdit** [comment]
Beyond even having alternate highlight colors, it might be worthwhile to implement different shaped icons (checkmark and x?) to the side of each frame.

I know we already have `Settings > Icons > Denote states with icons...`, but that doesn't effectively assist people with colorblindness, since the icons are both the same half-square triangle shape.

**Comment by YoshiRulz** [comment]
Reopening because that ^ includes unhelpful labels for where each colour is actually used (because I'm not sure).

**Comment by vadosnaprimer** [comment]
![изображение](https://user-images.githubusercontent.com/7092625/205014821-66e0fb37-2130-49f5-9173-1b724b897dd3.png)

Is this good enough?

**Comment by YoshiRulz** [comment]
It's so good I feel I now understand what the colours are for.
