### ISSUE TITLE
Savestate loading is nondeterministic in Octoshock

### ISSUE THREAD

**Issue by Zinfidel** [TASEmulators/BizHawk#2214]
This affects BizHawk 2.4.2, and in this example the Octoshock Core.

Core: Octoshock
BIOS: ps-30a.bin
Game: Ehrgeiz - God Bless The Ring (SHA1: 0BDBC7F0)

Here is the .tasjproj file: https://mega.nz/file/GQ4QhADB#kYGirVC5PLN67ueFtCM6xg60N4SBbHJV_gs82E39oTQ

### Reproduction
Video of these reproduction steps: https://gfycat.com/conventionalelasticcygnet  (click the "SD" wheel to get a larger video)

This .tasproj can be made to consistently desynchronize via the following steps:
1. Load Ehrgeiz into BizHawk
1. Open TASTudio
1. Open the attached .tasproj. There should be greenzone indication for the markers up to "Godhand End", but no greenzone indication for "Shuwen Start."
1. Double click on "Godhand End" in the markers.
1. OPTIONAL: Unpause the emulator if necessary to let the movie play
1. Observe the behavior when the match with Lee Shuwen starts. Godhand moves around a bit, Godhand attacks, and eventually Shuwen performs an interrupt.
1. OPTIONAL: Double click on "Shuwen Start" again. Observe that the match plays out the same way.
1. Double click on "Godhand End" again. Allow the movie to play.
1. Observe now that the match with Shuwen is different and correct. Godhand places a mine, then lands a combo on Shuwen while he is in midair.

### Notes
I've made a number of TASes of this game with versions < 2.4.0 and never encountered this before.

No cheats or any kind of memory manipulation at all has ever ocurred on this .tasproj. Branches HAVE been created and deleted, including branches around the area where the desynchs occur. I have a backup with these branches, but the desynch behavior is much harder to reproduce with them.

Previous to this issue, I had the .tasproj in a state where double clicking on "Godhand End" would always cause the Shuwen match to desynchronize, regardless of greenzone presence, whereas clicking on "Godhand Start" would always synchronize correctly. Extremely unfortunately, I lost this state due to forgetting to disable autosave while messing with it, but if I ever get a .tasproj with this behavior again I will update this issue.

Please get a hold of me on the TASVideos discord if any files need to be furnished to aid developers.

**Comment by nattthebear** [comment]
Is this a tastudio issue or can you get a similar desync with a non-tastudio movie?

**Comment by Zinfidel** [comment]
This is an issue with TAStudio _as far as I can tell._ To test, I exported a bk2 from the .tasproj in both a desync state and a correct state. A diff of the input log reveals that they are identical. Running the bk2s without TAStudio has correct behavior and syncs up.

**Comment by YoshiRulz** [comment]
see also https://github.com/TASVideos/BizHawk/issues/2186#issuecomment-653453849

**Comment by RetroEdit** [comment]
This is not a TAStudio-specific issue. Here's a simpler way to reproduce savestates being nondeterministic in Octoshock:

Export the movie mentioned here to `.bk2`. Play the movie and save a savestate on frame 9092. Then continuing playing (having not loaded a savestate). The TAS will execute as expected, doing the jump to dodge the hits.

*Then*, close and reopen said movie. Load the same savestate; the TAS will desync and just get hit instead of jumping over and dodging. Finally, load the same savestate a second time. The TAS will then exhibit the proper behavior. You don't even need two separate savestates to exhibit this behavior.

I'll try and find the frame on which a savestate causes a desyncs so this can be reproduced more efficiently.

----

Files included for convenience:

[2214_desync_savestate.zip](https://github.com/TASVideos/BizHawk/files/4894639/2214_desync_savestate.zip)

**Comment by zeromus** [comment]
He dodged every time, I couldn't see it happen. The dude doesnt take a hit until the movie runs out and then he gets thrown

**Comment by Zinfidel** [comment]
@zeromus Did you attempt to reproduce with both the .tasproj and the bk2s or just one of them? The .tasproj has bad savestates built-in so maybe that will do it?

**Comment by zeromus** [comment]
I just used the bk2 and made my own savestates. I just loaded 9092 from the tasproj twice and never saw anything different from the dude jumping over an attack and then using some kind of explosive heel kick

**Comment by RetroEdit** [comment]
@zeromus Did you completely close and reopen the game, then load the movie, and then load the savestate? From what I observed, the desync only happens the first time you load the savestate just after the game/movie has loaded.

(I also started the emulator paused).

**Comment by zeromus** [comment]
well, just now, i did it all on a fresh load of bizhawk. open bizhawk, open rom, drag tasproj, pause, load 9092 from tasproj.
or: open bizhawk, open rom, open tasproj, click through errors about markers, pause, go back to 9092. 
still never once seen it do anything different

**Comment by RetroEdit** [comment]
Huh. I mainly had it happen with the `.bk2`, though I did reproduce with the `.tasproj`. Did you try the savestates I attached with a `.bk2` (which were all created without interference from game boot-up, though I didn't completely close BizHawk between creating them, just the open game). I'm curious if my savestates would be different than yours (they shouldn't, obviously).

**Comment by zeromus** [comment]
None of the 3 you gave desync for me, ever

**Comment by Zinfidel** [comment]
> well, just now, i did it all on a fresh load of bizhawk. open bizhawk, open rom, drag tasproj, pause, load 9092 from tasproj.
> or: open bizhawk, open rom, open tasproj, click through errors about markers, pause, go back to 9092.
> still never once seen it do anything different

Errors about markers? I never saw anything like that on my side. Is there maybe some other factor there that needs consideration? BIOS? Mednafen settings? Maybe TAStudio settings? I modify my savestate history settings for both files and in-memory, perhaps those are relevant to the problem? Just in case, I'm going to list out all of the things that I think could somehow be related to this that I have set:
- Profile is set to Tool-Assisted Speedruns mode
- Speed/Skip
  - Clock Throttle
  - Auto-minimize Skipping
  - Skip 0
  - Speed 100%
- Savestate History Settings:
  - Memory Usage Capacity: 2048
  - Memory Usage Divider: 226 KB
  - File Capacity: 512 MB
  - Gap: 8
- PSX Options
  - Pixel Pro
  - Emulate Sector Errors **unchecked**
  - Weave
  - No clipping
- BIOS
  - ps-30a.bin, Version 3.0 11/18/96 A, used on SCPH-5501

**Comment by zeromus** [comment]
Apparently it happens infrequently, or infrequently only when dragging a tasproj into the markers list.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.EmuHawk.MarkerControl.get_Markers() in B:\git\bizhawk\src\BizHawk.Client.EmuHawk\tools\TAStudio\MarkerControl.cs:line 16
   at BizHawk.Client.EmuHawk.MarkerControl.MarkerView_QueryItemBkColor(Int32 index, RollColumn column, Color& color) in B:\git\bizhawk\src\BizHawk.Client.EmuHawk\tools\TAStudio\MarkerControl.cs:line 61
   at BizHawk.Client.EmuHawk.InputRoll.DoBackGroundCallback(List`1 visibleColumns, Rectangle rect, Int32 firstVisibleRow, Int32 lastVisibleRow) in B:\git\bizhawk\src\BizHawk.Client.EmuHawk\CustomControls\InputRoll\InputRoll.Drawing.cs:line 613
   at BizHawk.Client.EmuHawk.InputRoll.DrawBg(List`1 visibleColumns, Rectangle rect, Int32 firstVisibleRow, Int32 lastVisibleRow) in B:\git\bizhawk\src\BizHawk.Client.EmuHawk\CustomControls\InputRoll\InputRoll.Drawing.cs:line 457
   at BizHawk.Client.EmuHawk.InputRoll.OnPaint(PaintEventArgs e) in B:\git\bizhawk\src\BizHawk.Client.EmuHawk\CustomControls\InputRoll\InputRoll.Drawing.cs:line 56
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Anyway, I finally saw the desync by letting the tasproj play from whatever frame it wants to resume at (is it 9984?)

Here's two timelines.
YOUR TASPROJ:
frame 9984 - begin, already in black loading scene
frame 10281 - scene appears
frame 10410 - GO!! appears

FROM 9092 -- OR 9807 (the last frame of the prior scene, safely speaking)
frame 9092 - could begin here
frame 9807 - last frame of prior scene
frame 10199 - scene appears
frame 10328 - GO!! appears

note that we have 129 frames in both cases from 'scene appears' to 'GO!!'
so we can be sure that the problem is not in that range.
The problem is most likely due to a problem in savestating the CD controller status, which you provoked by loading states inside that region.

I would prefer to shitcan octoshock and let natt do it as a waterbox core, but promised I'd look into this as a favor for now.

Consequently, I feel decent about advising you to not do anything funny when the disc is loading. You might be able to get through your tas that way.

If someone else has this problem in a game where it's not so easily avoidable, I can debug what the problem is -- or maybe retroedit can by using these details. Now that the problem is KNOWN, we can compare a relatively small range of savestate histories and know where to look for discrepancies

**Comment by Zinfidel** [comment]
Oh I finished this TAS a few days ago - like you said, in my case this issue was easy to work around by simply letting the movie play back from some earlier state that is correct. Knowing that savestates during CD access is the likely culprit will be helpful going forward though.

On the topic of doing away with octoshock entirely, currently a "fix" for this problem is... using BizHawk 2.4.0. I'm guessing the upstream mednafen pull introduced this issue, and while I generally am a proponent of always using the latest, I've made several Ehrgeiz TASes with TAStudio on 2.40 (and earlier) without this issue. If the interim between a waterboxed mednafen and now is going to be long, perhaps a roll back of octoshock is in order?

**Comment by zeromus** [comment]
No, a review of the changes is in order.

**Comment by ThunderAxe31** [comment]
I think I discovered out what happens. Here are the repro steps:
1. Get any development build (I used the latest, #aa74209, but I got the same result from a pre-2.4 build, #185337d)
2. Open any PSX USA game
3. Launch TAStudio
4. Let it emulate for some seconds
5. Pause emulation
6. Go to TAStudio window > Edit menu > Savestate History Integrity Check (this feature only exists in dev builds)
7. Repeat step 6 a bunch of times and see if you get different results.

Most of the time I get "Bad data between frames 36 and 43", but I also got all kind of other results, even getting "Integrity Check passed" sometimes. It's clear that we're dealing with undeterministic emulation here. I wonder if this Integrity Check feature emulates in Fast Forward or Turbo mode.

**Comment by zeromus** [comment]
Please don't put variables such as "any" and "some" in your bug report when you are obviously in possession of concrete variable values.

**Comment by Samtastic1** [comment]
This is happening with me with Bizhawk 2.5.1.

**Comment by CasualPokePlayer** [comment]
Likely nonissue for Nymashock.
