### ISSUE TITLE
Switch pro controller not supported

### ISSUE THREAD

**Issue by pacmanboss256** [TASEmulators/BizHawk#2319]
Switch Pro controller with betterjoy doesn't work; the ABXY buttons are detected as constantly being pressed and unpressed as well as some other buttons. Oddly enough the joystick works fine.

**Comment by YoshiRulz** [comment]
*In general* we can't promise any third-party gamepad drivers will work with EmuHawk. That said, try changing `Config` > `Customize...` > `Input Method` to "DirectInput" and restarting EmuHawk. A quick read of their readme suggests it needs the Windows-only gamepad APIs.

**Comment by pacmanboss256** [comment]
I tried that and it still didnt work. even using the built in driver didnt seem to do anything

**Comment by SepticShocker** [comment]
I know this thread is almost a month old, but even if you've already found a solution, maybe this could help other users with the same problem. It's most likely an issue with Windows detecting both the Pro Controller itself and the virtualised 360 gamepad at the same time. This is where HIDGuardian that comes bundled with BetterJoy comes in. Here's the process I went through to fix a similar issue that I had when installing the most recent version of BetterJoy after a CLEAN reinstall of the drivers (that means making sure that you ran "HIDGuardian Uninstall (Run as Admin)" .bat file):

1. In the current version (6.3 I believe) there should be a .bat file under BetterJoy_v6.3_x64>Drivers>HIDGuardian called HIDGuardian Install. Simply run that as admin to install the drivers.

1.  Then go to http://localhost:26762/ in your browser. This should bring up a page called HIDGuardian Configuration (if it doesn't appear and shows as "Server not Found" or something similar, then the HIDGuardian drivers were not installed correctly).

1. Then it's just a means of making sure that under the "Currently affected devices" list that the Pro Controller is under it. If it's not then click the "Hide" button next to its listing under "Available USB/HID Devices".

1. Finally just unplug and reconnect the Pro Controller and everything should work as intended. To be sure then go into "Setup USB Game Conrollers" in Windows either through the search option or Control Panel.

An extra bit you can do to be sure that you won't have to add your controller into the "Currently affected devices" list is to go into the .config file in BetterJoy's folder and edit the following line to "false": 

"add key="PurgeAffectedDevices" value="**false**""

I also set this line to "-1" to make sure that as long as the controller is plugged it, it won't disconnect due to inactivity (This is just personal preference on my part):

"add key="PowerOffInactivity" value="**-1**""


I hope this is able to help you or anyone else who finds this thread!

**Comment by CasualPokePlayer** [comment]
This should no longer be an actual issue with the new SDL2 input backend, which picks up the controller with a low level HIDAPI driver.

I suspect the actual issue here is that DInput is mistakenly picking up the gyros in the Pro Controller as buttons, and so you end up with press/unpress hell (that's bypassed when using SDL2 with it using HIDAPI magic)

**Comment by CasualPokePlayer** [comment]
I've been using Switch Pro Controller for a while with the SDL2 backend and it works flawlessly, so considering this issue fixed.
