### ISSUE TITLE
[mgba core] skip bios is ignored when recording

### ISSUE THREAD

**Issue by InfamousKnight** [TASEmulators/BizHawk#2465]
The bios needs to be skipped when recording a movie file with homebrew games. It seems running homebrew requires bios to be skipped. When recording a movie, this setting gets ignored.

Tested on the Linux build. Not sure if same happens on windows.

Game I tested was ballistic.

**Comment by nattthebear** [comment]
This is intentional, but I am not against changing it.  Deterministic mode forces bios on because that's what's good for TASing, but it's not really determinism related.

It would be nice if hacks and homebrews actually worked and didn't need accuracy reducing hacks, but we can't fix that.

**Comment by zeromus** [comment]
don't these games just fail because their crc is wrong or something? if not that then if the game has to be run without the bios, it's dependent on a particular initialization state which might even vary between emulators so the game isn't very robust at all. which I will quite believe. but if it's just the crc we could correct that when booting the rom

**Comment by nattthebear** [comment]
I have not investigated this particular game, but yes, the most likely cause is that certain header fields are not set right and the official bios is rejecting them.  If that is the case, then dynamically patching like https://github.com/devkitPro/gba-tools/blob/master/src/gbafix.c would fix things.

**Comment by YoshiRulz** [comment]
By homebrew I assume we're talking about roms which aren't in the gamedb, in which case the user really should have control over whether the BIOS is used. Can we allow that with a C#-side change?

**Comment by CasualPokePlayer** [comment]
I'm not sure if this change was actually needed, seems that the bios is meant to be force skipped if mGBA detects that the logo is bad (and thus bios would refuse to boot the game) https://github.com/mgba-emu/mgba/blob/6159c5a70b6a92cb18948e9e1d7d214b3cdc9a48/src/gba/core.c#L693-L697

**Comment by InfamousKnight** [comment]
There's a way around this though. You can always record from save state.

**Comment by CasualPokePlayer** [comment]
Actually seems that mGBA is intended to skip the bios for homebrew such as the one mentioned in OP anyways as it is a multiboot rom (normally there is a process of sending that through serial in the GBA BIOS but that's not emulated in this case, so mGBA just skips bios). Except the multiboot detection at the skip bios stage is faulty so the bios doesn't get skipped.

https://github.com/mgba-emu/mgba/pull/2754 would resolve that core side, but otherwise I guess the skip bios can be allowed for movies until mGBA has this issue resolved on their side.
