### ISSUE TITLE
Controller config priority regression - Feature removed that I use... not clear why

### ISSUE THREAD

**Issue by weatherton** [TASEmulators/BizHawk#2752]
### Summary
Working on Mario Kart 64 TAS update, tried updating from 2.3 to 2.6.1 and realized that the ability to configure controller priority was no longer available. It looks like this was actually removed intentionally ( bd1c3cb991415837d5e7006c1f81c8342adcbd20 ) I'm not clear why though. When TASing with a keyboard, especially for Mario Kart 64, having being able to have key priority allows a much simpler, much less error prone sequence of key strokes to execute mini-turbos.

**Comment by YoshiRulz** [comment]
Do you mean this? It's also a hotkey under `General`.
![Screenshot_20210525_132428](https://user-images.githubusercontent.com/13409956/119435011-b9fdf000-bd5c-11eb-9d6d-2cf973dd9e1d.png)

**Comment by nattthebear** [comment]
We talked about this one offline a while back.  The basic options for what to do when two opposite directions are held down at once:

1. "Allow": Send both signals to the core
2. "Forbid": Send neither signal to the core
3. Send the one that was first pressed most recently to the core.
4. Send the one that was first pressed least recently to the core.
5. Send one particular constant direction signal that never changes.

1 is needed for some precision TASing, but also can cause glitched up behaviors in some games, and since real dpads generally didn't allow it (*), one of 2-5 is needed for casual play.  When doing casual realtime play, it's usually difficult to distinguish between 2-5, but not impossible.  I think 3 is the best, but since there is little realtime difference and I couldn't come up with a compelling use case we just dropped it for 2.  I was not aware of a real use for this feature when TASing.

Paging @adelikat as he was heavily involved in this decision.

**Comment by Myth197** [comment]
Myself and a few other users have remained on 2.4.2 purely because of the removal of this option in 2.5. We would like to upgrade to the latest version for greater tool support, however simply cannot due to the restrictions on the controls the lack of this option causes.

I hope this doesn't become a forgotten feature, erroneously assumed to not have a purpose.

**Comment by Henny022** [comment]
I wasn't aware of this, because I personally don't use it, but this new behaviour seems a bit too restrictive.
I also don't agree with adelikat's statement in their commit message that priority vs. forbid does not matter, because sending some legal input to the core vs. just drop all input seems like a bit of a difference.

**Comment by nattthebear** [comment]
We should reinstate this feature.  Looking again at the code, I'm not seeing any compelling reason it was removed.  It's ~100LOC that was well isolated to a single file and was reasonably easy to understand.  It didn't suffer from any of the intertwined complexity problems that we have in some other parts of the app.
