### ISSUE TITLE
BizHawk Crashes after selecting a core like DOSBox

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#2794]
### Summary
If we try to select a libretro core like latest version of DOSBox Libretro Core, then BizHawk will crash right after we select it. If that was supposed to be as intended, then why the heck is the point of adding libretro feature!?
### Repro
1. Select "Open Advanced" in File
2. Load latest version of DOSBox Libretro core
3. BizHawk Crashes after we select it. Interstingly, this bypasses BizHawk crash handler, causing no error messages to appear.

If this is as intended, then BizHawk is supposed to crash _after_ we launch a game, not _before_!
What is even causing this and why!?
### Host env.
BizHawk 2.6.2 Win10
BizHawk 2.4.2 Win10

**Comment by getCursorsExe** [comment]
Used Visual Studio 2019 to check what is going on, and I then see, that BizHawk was "trying to access and read or save secured memory". Excuse me, WHY BIZHAWK IS EVEN DOING THIS!?

**Comment by YoshiRulz** [comment]
From the stacktrace, the problem seems to be with these unsafe operations.
https://github.com/TASVideos/BizHawk/blob/40c53e0c1f1238cf02089ffc8509ab43eba31229/src/BizHawk.Emulation.Cores/Libretro/LibretroApi.cs#L58-L62
The pointer returned by `DllInit` is either outside valid memory, or points to something that's not laid out as expected (`CommStruct`, line 174) causing that read to continue past the end of valid memory.

**Comment by getCursorsExe** [comment]
This crash seems to happen in 32-bit cores only.

**Comment by CasualPokePlayer** [comment]
Does this still occur in 2.9 dev?

**Comment by getCursorsExe** [comment]
No.

**Comment by getCursorsExe** [comment]
This indicates a regression from 2.5.
