### ISSUE TITLE
[mGBA] While within the BIOS, loading a savestate made on frame 6 or 7 crashes BIOS

### ISSUE THREAD

**Issue by CasualPokePlayer** [TASEmulators/BizHawk#2938]
Repro, Open TAStudio -> Play some frames -> while still in BIOS, click frame 7 -> crash

Doing the same without TAStudio (manually advancing to frame 7) also crashes

Doing the same on frame 6 has the same result

**Comment by getCursorsExe** [comment]
Have you got the same behaviour on old VBA-Next? (go to BizHawk 2.4.2)

**Comment by CasualPokePlayer** [comment]
> 
> 
> Have you got the same behaviour on old VBA-Next? (go to BizHawk 2.4.2)

What does a different core have to do with a savestate issue.

**Comment by getCursorsExe** [comment]
I don't actually know, should waterboxing mGBA fix this issue?

**Comment by vadosnaprimer** [comment]
> I don't actually know, should waterboxing mGBA fix this issue?

Stop making irrelevant comments or you will be banned.

**Comment by getCursorsExe** [comment]
I did not encounter this issue in 2.6.2. (even interim builds)

**Comment by Spikestuff** [comment]
> Repro, Open TAStudio -> Play some frames -> while still in BIOS, click frame 7 -> crash

Surprisingly easy to replicate, for me it's frame 7/8 and it'll end up crashing the bios:
![image](https://user-images.githubusercontent.com/12412764/135277719-a61e86f4-41a5-4ec1-a868-ce65d2908cbb.png)

And because I have humor I decided to use _Crash Bandicoot 2: N-Tranced_ for a quick check.
Tested on the latest [master dev build](https://github.com/TASVideos/BizHawk/commit/340352eb69fa45ac46c1ddc5a5202f09a3d645de) and fork, as well as checking on 2.6.2.

**Comment by endrift** [comment]
Is this still a problem on latest BizHawk?

**Comment by CasualPokePlayer** [comment]
Seems to have been fixed between 2.8 and latest master.
