### ISSUE TITLE
`IndexOutOfRangeException` sometimes when getting registry values for Windows version check

### ISSUE THREAD

**Issue by ScowlingZebra** [TASEmulators/BizHawk#2972]
![image](https://user-images.githubusercontent.com/66571547/137934600-02b54cb4-6df3-4b07-bcfe-b00ebacefe39.png)
Anyone know how to fix this?

**Comment by YoshiRulz** [comment]
It would be "start EmuHawk". Please run these three commands in PowerShell and copy-paste the output like I have.
```
PS C:\Users\groom> REG QUERY "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /V CurrentVersion

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
    CurrentVersion    REG_SZ    6.3

PS C:\Users\groom> REG QUERY "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /V ProductName

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
    ProductName    REG_SZ    Windows 10 Home

PS C:\Users\groom> REG QUERY "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /V ReleaseId

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
    ReleaseId    REG_SZ    2004
```

**Comment by YoshiRulz** [comment]
From https://github.com/TASEmulators/BizHawk/issues/3194#issuecomment-1083468928, it seems this only affects Win10 *Education* editon.

Suggested workaround of replacing `REG QUERY` shell call w/ `Microsoft.Win32.Registry` isn't possible because the latter isn't in .NET Standard (even though it's in both .NET Framework and .NET Core, again why).
