### ISSUE TITLE
On some SNES cores, the resolution for 2x Window Size width is 1 pixel less than intended

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3046]
Affected cores:
Snes9x
BSNES
BSNESv115+

Faust does not have this issue.

**Comment by YoshiRulz** [comment]
I can confirm they're *different*, but I couldn't say which is correct.

**Comment by getCursorsExe** [comment]
You can try the 240p Test Suite to see which core is affected or not (use Color Bleed Check)

**Comment by zeromus** [comment]
What do you think is intended and why?

**Comment by Morilli** [comment]
This is due to aspect ratio correction on display being done, most accurately on the new bsnes core by using the established "most correct" value of `64/49 * height` (which is ~292.57 for a height of 224), whereas snes9x and old bsnes hardcode 293 for the default x1 resolution of `256x224`. Faust hardcodes 292. So, multiplying this value by 2 multiplies the error by 2 and results in the pixel difference you're seeing.

I'm not gonna dive into the aspect ratio correction discussion or which of those is correct here, but fwiw Faust just provides a different effective aspect ratio than the other cores, which results in the difference you're seeing.
