### ISSUE TITLE
"Close and reload ROM" from Firmware Manager from missing FW dialog causes assertion to fail

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#3054]
Specifically this one in `MainForm.LoadRomInternal`:
https://github.com/TASEmulators/BizHawk/blob/853b0fdd85ebf9d82184ebf80d63707d2f16d568/src/BizHawk.Client.EmuHawk/MainForm.cs#L3690-L3691

~~This must be a regression, but I haven't checked from when.~~ Between 2.4.2 and 2.5. I don't think the [commit history](https://github.com/TASEmulators/BizHawk/commits/2.5/src/BizHawk.Client.EmuHawk/MainForm.cs) there is helpful, others are welcome to look or bisect further.

FWIW my PR #2868 does **not** fix this.

**Comment by scrimpeh** [comment]
I think the issue is in [RomLoader.cs:751](https://github.com/TASEmulators/BizHawk/blob/acbbd946e7d400caa23994532d53ee81bede98a1/src/BizHawk.Client.Common/RomLoader.cs#L751

The args need to be constructed with the constructor that takes the rom path. That needs to be passed in from outside, which was probably dropped from some refactoring.

I would honestly just ditch the "Reload" button entirely, it just causes architectural pain.
