### ISSUE TITLE
Put a flag in the bk2 header for VS system

### ISSUE THREAD

**Issue by vadosnaprimer** [TASEmulators/BizHawk#3055]
VS is a variation of NES in a way, but not directly compatible. There is a bunch of VS games that come as iNES images, and NESHawk seems to know how to load them. In order to have a dedicated system for this on the site, we need NESHawk to mark VS movies in some way. @alyosha-tas is there a definitive way to tell it's a VS game? Are all VS games emulated currently?

**Comment by Fortranm** [comment]
https://tasvideos.org/Forum/Topics/12519?CurrentPage=81&Highlight=510672#510672
On a related note, Bizhawk currently doesn't seem to be able to run headerless VS rom files even though those are the ones listed in gamedb.

**Comment by alyosha-tas** [comment]
VS hasn't seen any working some time, some stuff like controllers is outdated and has open issues. But I believe all the games do work, they are identified by `NES._isVS` once a game is loaded. Headerless games cant run because only the mapper is in he DB, not other necessary information like PRG size.
