### ISSUE TITLE
[GB/GBC] Make GBA mode default for TASing profile

### ISSUE THREAD

**Issue by ThunderAxe31** [TASEmulators/BizHawk#3101]
GBA mode is the suggested sync setting for TASing GB and GBC games, with the exceptions being so rare that they weren't encountered yet. So, in my opinion, it should be set automatically when someone picks the "Tool-assisted Speedruns" as profile configuration. This applies to all three cores, gambatte, GBHawk, Sameboy, for both GB and GBC games.

**Comment by ThunderAxe31** [comment]
Thinking about it again, there are some GB games that don't work well in GBC or GBA mode, due to LCD timings, color palettes, or RNG issues. Also, some people may simply don't like it.

We may still want to automatically set GBA mode for TASing only GBC games, but that would bloat the program with excessive conditionals, wouldn't it?

**Comment by nattthebear** [comment]
Bizhawk has no governance of its own.  All decisions in it can be overridden at any point in time by the TASVideos staff, and those rulings are final.  The TASVideos staff made this decision.  Unless you can convince them otherwise, it will remain that way.

https://github.com/TASEmulators/BizHawk/commit/63f9de42a732a95415fc1ea5521fd7364dd54654
