### ISSUE TITLE
DSi firmwares have no checksum

### ISSUE THREAD

**Issue by BegaDrive** [TASEmulators/BizHawk#3159]
Bizhawk v2.8 windows x64

![bh](https://user-images.githubusercontent.com/97917453/154838129-c6085c44-35b2-49ba-a991-33876f612d66.jpg)

**Comment by YoshiRulz** [comment]
For technical reasons, we can't put one or more "correct" hashes there. (It probably shouldn't be the all-zeroes hash though @CasualPokePlayer).

**Comment by CasualPokePlayer** [comment]
NAND is console unique along with DSi BIOS files due to encryption. There is no one true hash to them. All zeros is just a filler hash.

**Comment by vadosnaprimer** [comment]
The missed detail here is actually that it's reporting the same exact info for all 4 DSi firmware files, even tho in the code they have different info but the hash is dummy.

**Comment by CasualPokePlayer** [comment]
Seems the issue is ultimately due to those entries taken from FirmwareFilesByHash. Which is a bit obvious in retrospect. Generally this isn't that bad as those hashes are not intended to match with any file. It screws up here however as the last thing with the dummy hash is what's actually in the Dict and thus what you see is that info for all firmwares with that hash.
