### ISSUE TITLE
Windows 10 Lock Screen breaks hotkeys

### ISSUE THREAD

**Issue by InfoManiac742** [TASEmulators/BizHawk#3161]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
On Windows 10, opening the lock screen with Win+L causes hotkeys/shortcuts to stop working. Gameplay controls continue to work as expected. The issue can sometimes resolve itself, but it's not clear exactly what fixes it (opening the Start menu worked one time, but not the next).

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Load any game
2. Use the Win+L button combination to go to the lock/login screen
3. Log back into Windows
4. Attempt to use any hotkey/button combination (such as saving/loading a savestate)

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.8; Windows 10 Home 21H2
- Doesn't occur in Bizhawk 2.7 or earlier

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by Morilli** [comment]
Git bisect gives accf0f038c565e97d41a8c28b4193e82285ae5c4 @YoshiRulz

**Comment by YoshiRulz** [comment]
Maybe this is why Super/Win was commented-out before? Please confirm dev build does not have this problem.

**Comment by InfoManiac742** [comment]
Can confirm that the issue has been fixed on the latest dev build.

**Comment by kexdd** [comment]
Windows+L has been fixed (Bizhawk no longer thinks that Windows key is being constantly held).
However, there's a similar (?) issue when pressing Ctrl+Shift+Escape to launch Task Manager.
Repro (Windows 10): Pause the game in Bizhawk 2.9.1, press Ctrl+Shift+Escape (this should open Task Manager), click back into Bizhawk window. Now Bizhawk thinks you're constantly holding Ctrl and Shift buttons. So when you try to unpause the emulator with the Pause key, it won't work (the emulator is registering Ctrl+Shift+Pause instead of just Pause). The workaround is to press Ctrl and Shift buttons once. This fixes the issue temporarily.
