### ISSUE TITLE
MMC1 SXROM Support

### ISSUE THREAD

**Issue by nintendesi** [TASEmulators/BizHawk#3168]
Hi, BizHawk doesn't properly support the SXROM variant of MMC1. The Z1M1 (Zelda 1 / Metroid 1) crossover randomizer requires SXROM and tests for 32 KB of bankable PRG-RAM on boot. This test fails on BizHawk.

[This nesdev link](https://wiki.nesdev.com/w/index.php/MMC1#SOROM.2C_SUROM_and_SXROM) contains the relevant information on SXROM. This is the error screen I see in BizHawk:
![screencap](https://cdn.discordapp.com/attachments/673454160850452481/943736429127823400/Screenshot_2022-02-16_231127.png)

SXROM is also used by the official Final Fantasy I+II multicart, so support for it is useful for the commercial library. I have not seen any other bug reports related to this issue.

Thanks for your time!

**Comment by nattthebear** [comment]
> SXROM is also used by the official Final Fantasy I+II multicart, so support for it is useful for the commercial library.

But you didn't actually try it, did you?  Otherwise you would have seen that it works.  To support the pirate garbage, you'll need a gamedb hack because there's no good way to infer SXROM from iNES (it guesses SUROM instead, which is more likely).

**Comment by Fiskbit** [comment]
FFI&II only works in BizHawk if BizHawk finds it in its database. Otherwise, it guesses the board incorrectly and supplies insufficient PRG-NVRAM, causing each game to clobber the other's saved data. This can be easily tested:

- Use a Final Fantasy I & II ROM with an NES 2.0 header (such as 4E 45 53 1A 20 00 12 08 00 00 90 07 00 00 00 00, specifying NES 2.0 and 32 KB PRG-NVRAM)
- Make a tiny modification to unused data to bypass BizHawk's database lookup (I changed $3FFFE in the headered ROM file from $2F to $20)
- Use the NesHawk core
- Save in FF1 by staying at the inn
- Save in FF2 using the pause menu on the overworld
- Try to load the game in FF1 and, instead, a new game will start
- Save again in FF1
- Try to load a game in FF2 and the first 2 files will be empty

I'm not sure what you're calling pirate garbage here, as FFI&II is an official multicart and Z1M1 is a randomizer, but neither game is at fault. If the amount of PRG-RAM specified in the header is greater than 16 KB, then the game cannot be SUROM, which is limited to 256 KB PRG-ROM and 16 KB PRG-RAM. SOROM is also out, because it is limited to 512 KB PRG-ROM and 8 KB PRG-RAM. The only remaining option is SXROM. NES 2.0 originally had MMC1 submappers for this, but because a heuristic is sufficient in selecting the correct board type, these were deprecated.

**Comment by nattthebear** [comment]
> FFI&II only works in BizHawk if BizHawk finds it in its database.

Yes, and there's only one FFI&II and it's in the database, so everything works.

> I'm not sure what you're calling pirate garbage here

Believe it or not, there were no officially licensed NES titles that combined Zelda and Metroid into one game.

Anyway, thanks for wasting my time reading that wall of text.  It changes nothing about what we already knew:  SXROM works, but there's no way to infer it from iNES.  We only have partial iNES 2 support because it's kind of crappy and not needed for any real games.
