### ISSUE TITLE
Libretro Gambatte core crashes BizHawk

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3216]
Outputs (0xc0000005) 'Access violation' in Visual Studio log.

**Comment by YoshiRulz** [comment]
Don't care.

**Comment by CasualPokePlayer** [comment]
Note it does work in this PR https://github.com/TASEmulators/BizHawk/pull/3212

iirc the issue is due to https://github.com/TASEmulators/BizHawk/blob/master/LibretroBridge/msvc/LibretroBridge.cpp#L304-L305 not setting *data to true (data is a pointer to a bool, and gambatte requires this set to true, otherwise it fails at load rom and it crashes BizHawk).

**Comment by CasualPokePlayer** [comment]
Fixed in https://github.com/TASEmulators/BizHawk/commit/25fb816988491463ba9312f99f6cad04840fd86b
