### ISSUE TITLE
TGB Dual libretro core crashes BizHawk when loaded more than twice

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3250]
8ca1e4a0 build

**Comment by YoshiRulz** [comment]
Which version? We have a bug template for a reason.

**Comment by CasualPokePlayer** [comment]
It seems to crash on the retro_unload_game call in Dispose(). Looking at the code, it's fairly easy to see why this crashes:
https://github.com/libretro/tgbdual-libretro/blob/1e0c4f931d8c5e859e6d3255d67247d7a2987434/libretro/libretro.cpp#L408
https://github.com/libretro/tgbdual-libretro/blob/1e0c4f931d8c5e859e6d3255d67247d7a2987434/libretro/libretro.cpp#L81
It gets malloc'd once on program init (although not in retro_init), then when retro_unload_game is called it gets free'd... and since it's never malloc'd again a subseqent retro_unload_game call causes it to free that pointer again which expectingly crashes. This is not the fault of BizHawk.

**Comment by getCursorsExe** [comment]
This crash did not happen BEFORE libretro was rewritten.

**Comment by CasualPokePlayer** [comment]
I believe that is due to it not calling unload game at all. Which that itself can just lead to memory leaks, another issue on its own.

BizHawk is currently doing the correct thing, libretro's shitty code is the core issue.

**Comment by getCursorsExe** [comment]
Before libretro was rewritten, the unload game was called client-side, but after libretro was rewritten, this is core-side now.

**Comment by getCursorsExe** [comment]
But before the libretro API was rewritten, there was a workaround that effectively avoids the crash.

**Comment by CasualPokePlayer** [comment]
There is no regression. It's more proper code crashing due to libretro's bad code. The bug always existed on libretro's side, it became visible in hawk when it did things more properly.
