### ISSUE TITLE
Implement SGB Emulation for SameBoy

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3251]
But, it's not like the old one from older versions.

**Comment by YoshiRulz** [comment]
Isn't the SGB emulation in BSNESv115+ just SameBoy?

**Comment by CasualPokePlayer** [comment]
> Isn't the SGB emulation in BSNESv115+ just SameBoy?

It is, BSNES emulates the SNES and SameBoy emulates the GB.

The main reason base SameBoy does not have its HLE SGB emulation exposed is due to not supporting SNES sound (unlike Gambatte's HLE SGB and our own old fork of SameBoy used before). With Gambatte gaining this SameBoy was dropped, and was readded for only GB/C using the latest upstream with *no* modifications.

There are already open issues about SNES audio in SameBoy, open an issue in Hawk if the SameBoy developer actually implements this feature (more likely you'll be waiting a *very* long time for this, if it ever happens).

**Comment by getCursorsExe** [comment]
The original BSNES core is the most inaccurate SGB core I have ever seen.

**Comment by CasualPokePlayer** [comment]
The old BSNES core uses Near's own GB emulator which is on par with VBA in terms of accuracy. BSNESv115 has SameBoy integration.

**Comment by getCursorsExe** [comment]
However, our old SameBoy core had issues with colors on screen, so LLE SGB emulation is not causing #2477.
BGB only relies on SNES CGRAM and Tile VRAM when we mean SGB, while keeping its' accuracy.
