### ISSUE TITLE
Left and Right Shift and Control Keys are not detected seperately anymore since 2.8, problem for C64

### ISSUE THREAD

**Issue by Zimond47** [TASEmulators/BizHawk#3257]
Also applies to the current Devbuild [95ecbe99]

You cannot bind "Left Shift" and "Right Shift" anymore, just "Shift". I noticed when I tried to load a game in C64Hawk because the default setting for the C64 Shift Keys are "Left/Right Shift" which do nothing now. You have to rebind them first to another key (or just Shift) to be able to write LOAD"*",8,1 

Version 2.7 seperated both keys.

**Comment by YoshiRulz** [comment]
Duplicate of #3184. (See https://github.com/TASEmulators/BizHawk/issues/3184#issuecomment-1116892773 for how to restore the old behaviour.)

**Comment by CasualPokePlayer** [comment]
This is an issue for C64 whose defaultl controls have LShift and LCtrl, which do not work at all with the now default merged L+R Shift.

**Comment by YoshiRulz** [comment]
> probably the merged L+R Shift/Ctrl should activate LShift/RShift/LCtrl/RCtrl when the merged Shift/Ctrl is pressed instead of just doing nothing

I anticipated this at the time, and made changing the setting also prompt for whether to fix keybinds:
https://github.com/TASEmulators/BizHawk/blob/cdeec7cfb44283424b0f3b8084887538425f8ec9/src/BizHawk.Client.EmuHawk/config/EmuHawkOptions.cs#L116-L123
So only the defaults need changing.

**Comment by vadosnaprimer** [comment]
If LShift/RShift/LCtrl/RCtrl were the problem, why did you remove everything else?

**Comment by YoshiRulz** [comment]
Conflicts. And I also don't think we should be eating up literally every available unmodified key.

**Comment by vadosnaprimer** [comment]
What kind of conflicts exactly?

**Comment by YoshiRulz** [comment]
https://github.com/TASEmulators/BizHawk/blob/fe2cd58bee84fe82be0af5cb604e85b2f43e091b/src/BizHawk.Client.Common/config/Binding.cs#L27
https://github.com/TASEmulators/BizHawk/blob/fe2cd58bee84fe82be0af5cb604e85b2f43e091b/src/BizHawk.Client.Common/config/Binding.cs#L30
https://github.com/TASEmulators/BizHawk/blob/fe2cd58bee84fe82be0af5cb604e85b2f43e091b/src/BizHawk.Client.Common/config/Binding.cs#L56-L57
https://github.com/TASEmulators/BizHawk/blob/fe2cd58bee84fe82be0af5cb604e85b2f43e091b/src/BizHawk.Client.Common/config/Binding.cs#L81-L102
To name but 26.

**Comment by vadosnaprimer** [comment]
Having to bind them allin order to play or TAS (with traditional method) for every single release is a much more annoying problem, than something nobody complained about in 10 years of being quite popular. If there's a problem with using the button that sets hotkey/input priority, it needs to be discussed, without silent removal of all the keyboard binds.

**Comment by CasualPokePlayer** [comment]
In practice all you're just doing is making is so the user rebinds every single key back to what the defaults were and they will have to learn how to use Toggle Key Priority (maybe by setting a hotkey or just clicking the icon in the UI)

**Comment by YoshiRulz** [comment]
There are other solutions that would give you (no conflicts OOTB) + (near-instant usable guest keyboard)—for example, we could add a dedicated button to bind some or all of the virtual keys to the host keyboard. I didn't pursue this because it would save less than 1 min per user per core, and would have involved more bikeshedding and time *I would have felt was wasted* because it wasn't going towards #1636.

**Comment by vadosnaprimer** [comment]
Would reverting https://github.com/TASEmulators/BizHawk/commit/ec3a23259cf0f9528aef661b9df51846997485f4 unfix this issue?

**Comment by YoshiRulz** [comment]
As written, yes. To avoid a regression you'd have to also change the default binds for all the virtual L/R modifier keys.

**Comment by vadosnaprimer** [comment]
I'm looking at it again and I fail to see how erasing all default keyboard bindings is even related to inability to distinguish between left and right modifiers. The latter it already solved by the option in Customize dialog. And the so-called "conflicts" with hotkeys are unavoiable and not relevant to this issue.

> And my belief that we shouldn't be using unmodified keys in default binds also extends to hotkeys

What belief? I don't remember ever having a proper discussion about it. What exactly is it based on and what exactly does it result in?

**Comment by YoshiRulz** [comment]
> I'm looking at it again and I fail to see how erasing all default keyboard bindings is even related to inability to distinguish between left and right modifiers. The latter it already solved by the option in Customize dialog. And the so-called "conflicts" with hotkeys are unavoiable and not relevant to this issue.

The problem posed in OP was that the default keybinds weren't working. I saw 2 options:
1. Update the defaults to be e.g. `Shift,LeftShift`. I couldn't in good conscience do that with find+replace, I would have had to check them all (and maybe find and fix some other problems in the process). I also wasn't sure if the migrator would choke on `Shift,LeftShift`.
2. Remove the defaults where they were bound to Shift. Which would have left a lot of partial default bindings, the worst of both worlds. But I could go further and remove the defaults for the whole keyboard, which both aligns with my desire for no unmodified keybinds, and leaves no room for partial layouts or conflicts with hotkeys. So I did that.

>> And my belief that we shouldn't be using unmodified keys in default binds also extends to hotkeys
>
> What belief? I don't remember ever having a proper discussion about it. What exactly is it based on and what exactly does it result in?

I was referring to an earlier comment in this thread. I then mentioned it in https://github.com/TASEmulators/BizHawk/issues/4012#issuecomment-2315684525. I've just now edited in more elaboration there, and I ask that we use that issue to move forward, whether that's by building out the one-click populate concept or something else.

**Comment by vadosnaprimer** [comment]
OP's problem was fixed by [exposing](https://github.com/TASEmulators/BizHawk/commit/ceb64cedb05039433563ef5048c2ace31780c274) a way to choose whether we want to merge or separate the modifiers. Old behavior was indeed available, probably even at the time the issue was created (as you pointed out in the first comment). I just tried it on master with ec3a23259cf0f9528aef661b9df51846997485f4 reverted and it's [perfect](https://tasvideos.org/Bizhawk/C64#Disk) (with merge modifiers disabled and controller buttons priority):

<img width="660" height="531" alt="Image" src="https://github.com/user-attachments/assets/277e173b-e503-4b24-8296-a1554641ac2c" />


> But I could go further and remove the defaults for the whole keyboard, which both aligns with my desire for no unmodified keybinds, and leaves no room for partial layouts or conflicts with hotkeys.

Turns out it was nobody else's desire, as evident by no issue reports regarding those problems for actual users over all the years blah blah...

> I've just now edited in more elaboration there, and I ask that we use that issue to move forward, whether that's by building out the one-click populate concept or something else.

That's fine, we'll discuss how to improve the system there. For the time being tho, I'm reverting ec3a23259cf0f9528aef661b9df51846997485f4 because it causes more problems than it's meant to fix, and whatever it was trying to fix will need to be done differently, upon a proper discussion over there.

I was just trying to figure out which exact fix will be undone by the reversion ([as you said](https://github.com/TASEmulators/BizHawk/issues/3257#issuecomment-1787685300)) but it looks like that commit fixed nothing to begin with. So we're just back to status quo for now.
