### ISSUE TITLE
Lag frame detection is broken in Gambatte without BootRom

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3269]
When Gambatte is booted without BootRom, BizHawk will interpret all lag frames as input-enabled frames, even though the game still ignores. This is noticeable when running Gameboy demos.

**Comment by CasualPokePlayer** [comment]
This is just due to the no bootrom code setting the joypad port open rather than closed (which is only "wrong" if booting up a DMG only game with the emulator set to GBC). This is only going to be noticable when the "game" doesn't ever actually interact with the joypad port (so the "games" this affects are just demos, or otherwise cases where the lag detection does not matter).

Not going to bother with this due to its fringe nature and in practice not "breaking" lag frame detection.
