### ISSUE TITLE
BizHawk crashes immediately when opening a rom with any libretro core

### ISSUE THREAD

**Issue by mnec20** [TASEmulators/BizHawk#3271]
### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
I'm running BizHawk 2.8 and everything's fine when using the built-in cores. The problem is that whenever I use Open Advanced to select a libretro core and a rom, BizHawk crashes immediately upon launching the game without any error showing. I tried cores for various MAME, flycast and dolphin. None of them work. heisenbug ?

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.8; Win10 Home 21H2; Intel/Intel

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by YoshiRulz** [comment]
They're not all going to work. I can't find the comment, but I think zeromus said something like "It's hard to implement everything because the Libretro API is poorly-defined and a bit of a moving target."

Of the ones I've tried, melonDS, ParaLLEl N64, and PPSSPP don't work, but BSNES Mercury does. If you need to emulate a system that BizHawk doesn't cover, your best bet is to use a dedicated emulator, or RetroArch as a last resort.
