### ISSUE TITLE
RAM Search for Waterboxed (SNES?) cores painfully slow

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#3296]
SMW title screen in Snes9x runs at ~400 fps unthrottled, but 6 fps upon opening RAM Search (-99%), regardless of settings. For comparison:
- SMW title screen in Faust also falls from ~400 fps to 6 fps (-99%)
- SMW title screen in old BSNES falls from ~145 fps to 6 fps (-96%)
- SMW title screen in new BSNES falls from ~190 fps to ~95 fps (-50%)
- Bonk's Adventure title screen in HyperNyma falls from ~500 fps to ~65 fps (-87%)
- Bonk's Adventure title screen in TurboNyma falls from ~300 fps to ~60 fps (-80%)
- Bonk's Adventure title screen in PCEHawk falls from ~330 fps to ~200 fps (-39%)
- SMB1 title screen in QuickNes falls from ~1600 fps to ~480 fps (-70%)
- SMB1 title screen in NesHawk falls from ~90 fps to ~80 fps (-11%)
- Pokémon Blue title screen in Gambatte falls from ~1180 fps to ~380 fps (-68%)
- Pokémon Blue title screen in SameBoy falls from ~370 fps to ~250 fps (-32%)
- Pokémon Blue title screen in GBHawk falls from ~140 fps to ~100 fps (-29%)

All in Release config at https://github.com/TASEmulators/BizHawk/commit/e88fa81358d7d8c16458c2a642f9f159204027c1 under Mono. It seems fully-managed cores lose 10–40% speed (though they're not very fast to begin with), unmanaged cores lose 70%, and Waterboxed cores lose 80–99%.

**Comment by CasualPokePlayer** [comment]
For me:

Pokemon Blue title screen in Gambatte ~560 fps -> ~210 fps (-62%)
Sonic 3 file select screen in Genplus-gx ~230 fps -> ~30 fps (-86%)
SMW title screen in Faust ~175 fps -> ~20 fps (-88%)
SMW title screen in SNES9x ~210 fps -> ~20 fps (-90%)
SMW title screen in old BSNES ~110 fps -> ~17 fps (-84%)
SMW title screen in new BSNES ~100 fps -> ~75 fps (-25%)

However, once results are cut down, speed returns by a fair degree, e.g. Gambatte ~210 -> ~360 once 7 results remain. I think this is just natural performance drop by the large number of reads done, even worse for some cores that go through delegates rather than IntPtr reads, even worse for waterbox as those need a monitor (EnterExit()), and obviously even worse when there's more reads done. That last point is largely why new BSNES is getting such a minor decrease... as it seems to default to searching through CARTRIDGE_RAM which is fairly small (2048 bytes).

**Comment by Morilli** [comment]
Ideally the structure would be changed to allow "bulk-peeking" bytes. The biggest overhead is the `EnterExit` wrapper itself; so getting the calls of that down to 1 per frame would already resolve most of the slowdown issues here.

**Comment by nattthebear** [comment]
Agreed.  The way to speed this up would be bulk peeks.

**Comment by CasualPokePlayer** [comment]
Bulk peeks wouldn't be an ultimate solution under the current code (or well, mainly standard WaterboxDomains) as a note, address manglers (ie for byte/word swapping) currently have PeekByte spammed (leading to the same situation as before). And wider than a byte bulk accesses (e.g. ushort/uint) also have the same issue of spamming PeekByte. Some adjustments would have to be made for these cases.

**Comment by vadosnaprimer** [comment]
I agree that implementing peek bigger than a single byte is long overdue!

**Comment by CasualPokePlayer** [comment]
https://github.com/TASEmulators/BizHawk/commit/596bd03ebe2a7721c42a8293dbf98e37e2413638 probably helps this, but there's definitely more that can be done.

**Comment by Morilli** [comment]
Profiling result from having the `CARTRIDGE_ROM` domain opened in ram search in Super Mario World (BSNESv115+ core) on fe22d61b3a11401121d30aaad894a000a2d40136:
![image](https://user-images.githubusercontent.com/35152647/177058444-0b9d7110-1c81-48f6-94e7-2a91996cc9de.png)

For reference; the `FrameAdvance` call takes only 2.5% of the total running time. I suppose garbage collection and mass churning of `EnterExit` calls are the main reason (those profiling results don't directly translate to a real run without profiler attached, but are probably still relevant).

**Comment by YoshiRulz** [comment]
Good job guys, as of https://github.com/TASEmulators/BizHawk/commit/9e90290b878527805703d7539c52029ff113d81f I'm now getting ~110 fps for Snes9x, ~95 fps for Faust, and ~70 fps for old BSNES.

**Comment by nattthebear** [comment]
`EnterExitWrapper` is used all over the place.  Is it really that slow, and why?  I don't want to litter the entire app with `try ... finally` if we can help it.

**Comment by CasualPokePlayer** [comment]
It's not particularly slow, although it the majority of the managed overhead here with Enter/Exit (measurements from Morilli with new BSNES: EnterExit wrapper: 50 fps, Enter / Exit: 70 fps, no Enter / Exit: 80-90 fps). The overhead comes from the allocation spam (something like 500k allocations per frame according to Morilli, which adds up a lot). You could revert it if you want I suppose. Though I think it could be fair if it is done in code that gets spam called (the 500k allocations per frame figure points to that being the case here).

**Comment by nattthebear** [comment]
I'm fine with leaving it as is for this callsite.  For other callsites, we might consider using a valuetype for the wrapper.  `using var` should work with that to avoid a heap allocation:

https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgJgIwFgBQyDMABGgQMIEDeOB1RhyALAQOID2LMAFAJRU2XY1BRAAwEAbgEMATgQDOBALwEAImFkAHFrICmUicG3cA3L2oBfU7SKMAghFktW7bpf5CayUR0kz5S1RpauvqGXDwC7hSWghYR5lSW+NYEAEISnFxRcUKeBACSAZqyEgBGENpyiipqRcEGxpaxlgDK1YE6evXhgm6RRADsBAB22gDuBM3GNI04TdiywFIArgDGwBMEIPmFWqXlOL3USQxttS7ZhwSxsUA=

**Comment by Morilli** [comment]
Can we consider this resolved now? Or would you like a further improve in performance?

From my testing, the remaining overhead seems to be due to excessively expensive internal logic which is running every frame:
![image](https://user-images.githubusercontent.com/35152647/178084341-cf13f26b-1b39-4725-942f-e571cdc7d227.png)
