### ISSUE TITLE
You cannot use Game Genie codes pointing to ROM at all in Genesis.

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3371]
I think this has to do with #3246.
Example: NKCA-LABR normally sets address 0x05442E to 0x0062. But #3246 prevents that from working.
This is due to all cheats pointing to M68K BUS memory domain, while cheats pointing to ROM should land on MD CART instead.

**Comment by ReyVGM** [comment]
What if you manually change the domain after adding the cheat, will it still work?

**Comment by getCursorsExe** [comment]
Yes it will.

**Comment by ReyVGM** [comment]
The problem is not that you can't use GG codes, the problem is that they point to the wrong domain?

**Comment by YoshiRulz** [comment]
Try [this dev build](https://gitlab.com/TASVideos/BizHawk/-/pipelines/650058544/builds).

edit: Closing as stale. My branch will remain around in the aether, if it disappears from this repo just hit me up and I'll get you a copy.

edit from the future: Fixed by https://github.com/TASEmulators/BizHawk/commit/28a93431700a924a1161d5f7909f5a987b9fce07.
