### ISSUE TITLE
[MelonDS] Hotel Dusk - Room 215, Chapter 8 puzzle is impossible

### ISSUE THREAD

**Issue by KawaiiFiveO** [TASEmulators/BizHawk#3397]
### Summary
ROM: 0823 - Hotel Dusk - Room 215 (USA).nds
Core: MelonDS

There is a puzzle in Chapter 8 that requires the player to spin a pencil using the touch screen. On BizHawk, the puzzle is impossible to complete, as the pencil will not spin after a certain point. I played the same save on DeSmuME and did not experience the same issue.

### Repro
1. Play Hotel Dusk (with attached save file, select the latest Chapter 8 save)
2. Examine the table with the tape player
3. Use the pencil on the unwound tape
4. Attempt to wind the tape using the touch screen

### Host env.
- BizHawk 2.8; Win10; AMD/nVidia

[Chapter 8 save.zip](https://github.com/TASEmulators/BizHawk/files/9644567/Chapter.8.save.zip)

![pencil](https://user-images.githubusercontent.com/49249543/192232955-7d769553-698e-4265-a7b2-f4d94ec4c183.png)

**Comment by Spikestuff** [comment]
So what happens in the [upstream that is melonDS](https://github.com/melonDS-emu/melonDS)?
Should this be an issue that they need to be aware of to correct?

**Comment by KawaiiFiveO** [comment]
I attempted the puzzle on MelonDS 0.9.4 and did not experience any issues completing it.

**Comment by CasualPokePlayer** [comment]
Trying this out myself, I could not complete this on DeSmuMe (0.9.13 and 0.9.11) nor BizHawk melonDS, but upstream melonDS I could.

**Comment by CasualPokePlayer** [comment]
Also, I tried this on latest master, still can't do it. I don't think this is a core issue, rather it may just be a "frontend issue." The only actual emulation difference between upstream and us concerns RTC emulation (which shouldn't be an issue here really, issue still occurs with real time RTC) and me hacking around the threaded renderer to make it work in waterbox (issue still occurs with single threaded rendering). It may be due to BizHawk sending touch coords every single frame, while melonDS just only sends touch coords on mouse press/move/release events, the frequency of which depending on what Qt does internally.

**Comment by KawaiiFiveO** [comment]
The version I used is labeled:

DeSmuME_0.9.13_x64.exe
