### ISSUE TITLE
System.DivideByZeroException at BSNESv115+ graphics debugger

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3398]
It's very hard to reproduce, but sometimes when messing with registers in debugger while the graphics debugger is open, you'll end up getting System.DivideByZeroException. According to Visual Studio Breakpoints, this crash happens at `var bg = si.BG[currMapEntryState.bgnum];`, which is at line 756 in BizHawk.Client.EmuHawk.SNESGraphicsDebugger.
I have no idea how to reproduce this, but it happens randomly when messing with debugger while graphics debugger is open.
The first System.DivideByZeroException found in EmuHawk.

**Comment by getCursorsExe** [comment]
Which I'm guesssing that `int baseTileNum = tiledataBaseAddr / tileSizeBytes;` at line 760 has `tileSizeBytes` is 0, crashing EmuHawk completely.

**Comment by YoshiRulz** [comment]
Yes, `bg.Bpp` here is populated from `SNESGraphicsDecoder.ModeBpps` which contains zeroes.
https://github.com/TASEmulators/BizHawk/blob/b84ef509ec195adf29cbe2635b8975809c0c127f/src/BizHawk.Client.EmuHawk/tools/SNES/SNESGraphicsDebugger.cs#L757-L760
Just looking at the code, I believe the way to reproduce this is to inspect BG4 when the `BG_MODE` register is any value besides 0.
I also believe this was broken *before* https://github.com/TASEmulators/BizHawk/commit/6f0953aaa38fc9ddc61ec8f3fb2bbba8dfa6ffa1 though, again, haven't tried it.

**Comment by Morilli** [comment]
Yeah, this definitely wasn't caused by my commit, as I have confirmed this same thing happens on release 2.6.1 with the old bsnes core.

That said, a lot of other code that works with the bpp explicitly checks for `bpp == 0` and early-returns or switches operations based on that, so that should probably be done here as well? Gonna ping @zeromus as he seems to have originally written this code.

Here's an example of how the `bg` variable looks when that exception occurs (reproduced using the "World Class Service Super Nintendo Tester" cartridge and the character test while having the snes graphics debugger open (debugger not needed)): 
![image](https://user-images.githubusercontent.com/35152647/192457915-efdc4b95-7588-41f9-b690-bc8176576ddb.png)

**Comment by zeromus** [comment]
checking for bpp==0 seems sensible. maybe this is used to determine when the BG is even existing (this would be separate from whether it's "enabled" perhaps? an unfortunate choice of terminology if so in retrospect)
