### ISSUE TITLE
Warn user if they record a movie using the casual profile.

### ISSUE THREAD

**Issue by CasualPokePlayer** [TASEmulators/BizHawk#3438]
Most users are probably unaware of the profile system even existing. A warning should appear if a movie is being recorded using the (default) casual profile.

**Comment by YoshiRulz** [comment]
While the selected profile is saved, it's not guaranteed that the rest of the settings are congruous with the profile. For instance, you could choose the TAS profile, then manually change the ~20 settings back.

**Comment by CasualPokePlayer** [comment]
If you selected the TAS profile, you know the profile system exists. This warning would be primarily for people who don't know the profile system even exists.

**Comment by YoshiRulz** [comment]
Fair. There's meant to be an onboarding thing in the status bar but it's too subtle and I'm not sure it always works. Maybe do something with that?

**Comment by RetroEdit** [comment]
See also: a351dcc55795ed6df8f62f6fb16f4be031fb27c3

**Comment by Morilli** [comment]
With https://github.com/TASEmulators/BizHawk/commit/a351dcc55795ed6df8f62f6fb16f4be031fb27c3, I don't think this is necessary anymore. 

I also generally disagree with warning just because the casual profile is selected. I personally like to have control over every setting, so I wouldn't want to use a button that silently changes however many settings for me that I might not like (especially knowing that many of them have been set years ago and not really double-checked again).

**Comment by CasualPokePlayer** [comment]
Yeah, the main purpose of this is just to get people aware of the profile system existing. It's not much of an issue with that commit in place.
