### ISSUE TITLE
Perfect Dark versions in Ares64

### ISSUE THREAD

**Issue by vadosnaprimer** [TASEmulators/BizHawk#3460]
I tried running 4 verified good versions of PD in the ares core (J, E, U 1.0, and U 1.1), and only U 1.0 works in latest dev build of hawk, the rest give a black screen, regardless of emulator and core settings. They all load fine in standalone ares in both v128 and latest release (I don't have vulkan).

**Comment by CasualPokePlayer** [comment]
See if 9420c8b21c0151efe4e32c82cd25a488fad98375 changes things

**Comment by vadosnaprimer** [comment]
Nope!

**Comment by CasualPokePlayer** [comment]
From testing I am guessing there is something weird wrt eeprom here. If I give PD a premade SaveRAM (e.g. launch mupen beforehand) it ends up booting just fine. Hex editor also shows weird activity in eeprom, with the first word connstantly changing (and the rest still at their default 0xFF).

**Comment by vadosnaprimer** [comment]
This may explain why it was randomly working and not working before, without any apparent reason (I tried the E version back then, on another OS).

**Comment by CasualPokePlayer** [comment]
This actually seems to present in upstream too. The issue occurs on hawk more due to a difference in default settings: BizHawk defaults to only player 1 having a controller connected and upstream defaults to all controllers connected. Disconnecting a controller upstream results in the same black screen behavior.

I would assume this is an inaccuracy on upstream's part anyways, I would doubt the game would not work correctly if all slots were disconnected. Granted, the fact that a "formatted" EEPROM seems to work might indicate the starting EEPROM state is unrealistic in ares (might be the case they would be preformatted? Or maybe more random state would avoid this issue).

**Comment by vadosnaprimer** [comment]
The E version now works in https://github.com/TASEmulators/BizHawk/commit/137634cf8958d1ee5498539355fbe3355063e8bc

**Comment by CasualPokePlayer** [comment]
Are you sure you aren't loading it with "good" SaveRAM?

**Comment by vadosnaprimer** [comment]
Uhhh I dunno how it happened. I haven't touched controllers when I grabbed the new build. Freezing now indeed........

**Comment by CasualPokePlayer** [comment]
This seems to have gotten fixed at some point (probably one of the upstream merges).
