### ISSUE TITLE
TAStudio `.bk2` export is disabled until a `.tasproj` is saved

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#3504]
This seems like an unnecessary restriction.

**Comment by Morilli** [comment]
The main reason this isn't trivial is because the file name needs to be determined before saving.
The default name is currently still "default.tasproj" but the user is prompted to choose a different one on saving the tasproj. Only then does the tasproj have a valid name set and bk2 saving can use that to save as .bk2.
The bk2 export button doesn't even prompt a filename at all, ever, at least currently.

**Comment by vadosnaprimer** [comment]
I think it'd be ideal if bk2 export had a proper file dialog. Because if you haven't renamed your tasproj after importing someone else's bk2, it will overwrite it and you can't help up, until you rename the tasproj, which creates its copy or requires closing it.
