### ISSUE TITLE
Hex Editor doesn't like GPGX VRAM

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#3516]
Endianness is set to `Unknown`:
https://github.com/TASEmulators/BizHawk/blob/a8964711642af7c3f6f3d7ac188deb6f5c26d3bd/src/BizHawk.Emulation.Cores/Consoles/Sega/gpgx64/GPGX.IMemoryDomains.cs#L32-L36
which should be treated the same as `Little` (on load only):
https://github.com/TASEmulators/BizHawk/blob/a8964711642af7c3f6f3d7ac188deb6f5c26d3bd/src/BizHawk.Client.EmuHawk/tools/HexEditor/HexEditor.cs#L223
but the endianness checkbox doesn't have any effect.

@nattthebear Any ideas?

**Comment by nattthebear** [comment]
It's been a while since I worked on this, so I'm going to talk through my understanding and assumptions to see if this makes sense to anyone or if I'm totally off my rocker.

MemoryDomain describes a byte oriented interface.  A memory domain is conceptually N 8 bit bytes in order, that are addressable at a single byte level.  So from that we have `PeekByte` and `PokeByte`.  These functions do not have a word size; they always return 8 bits.  They have no concept of endian; as the addressing system is defined in integer numbers of bytes and there is no way to independently address a 4 bit "nibble" to observe an endianness within the bytes.

Building on top of that, we can define the standard concepts of endian and wordsize in the usual way for handling multibyte quantities.  There are two different endians and wordsizes that can be relevant:  The preferred viewing of the domain, and the one we're actually using to observe it.  Since we know the underlying architecture of the source system, we can say that a particular domain is likely interpreted by its host architecture and code as "big endian, 2 byte words", and so that would be the preferred way for a hex editor to display it.  But because the guest system can be running arbitrary code that can do arbitrary things, other representations might still be useful and we allow them all.

So, if I ask for a 2 byte read of big endian from address 0, then that should always be exactly equal to
```
PeekByte(0) << 8 | PeekByte(1)
```
If I ask for a 4 byte read of little endian from address 0, then that should always be exactly equal to
```
PeekByte(0) | PeekByte(1) << 8 | PeekByte(2) << 16 | PeekByte(3) << 24
```

And this is true regardless of what the domain has defined for endian and wordsize.  So `MemoryDomain` has `PeekByte` and `PokeByte`, as they're the fundamental API needed, and `WordSize` and `EndianType`, as they're useful metadata for debugging tools.  Why then can memory domains directly implement methods such as `PeekUshort`?  Performance, of course.  Think of the underlying data storage backing the memory domain.  As BizHawk runs exclusively on little endian hardware, but many of the guest systems are big endian and most commonly do multi-byte word reads and writes internally, it can make more sense to store the guest memory swapped in host memory.  This means that `PeekByte` and `PokeByte` are non-trivial implementations, and it very well may be much faster to do `PeekUshort(addr, bigEndian: true)` as a direct operation then as a combination of two byte peeks, plus multiple swizzles, plus reassembly.

But in this debugging interface we're always giving a way for the host to access the bytes however it pleases.  So long as the guest chooses a canonical byte ordering of its own (typically matching the guest CPU's notions of addressing), and a canonical byte value at each address (typically matching the guest CPU's own read8/write8 opcode results), the rest is completely determined and all of the other memorydomain methods are just optimizations.  So reiterating from above,

```
PeekUshort(0, true)
```
Is always, in every situation, with no exception, exactly equal to
```
PeekByte(0) << 8 | PeekByte(1)
```

With that in mind, it's simple to trace down the problem here:  `MemoryDomainDelegate`'s [implementation](https://github.com/TASVideos/BizHawk/blob/a8964711642af7c3f6f3d7ac188deb6f5c26d3bd/src/BizHawk.Emulation.Common/Base%20Implementations/MemoryDomainImpls.cs#L53) of `BulkPeekUshort` and `BulkPeekUint` are both completely wrong.  The passed `bigEndian` argument is silently discarded and substituted with the domain's preferred endian.  Changing a domain's preferred endian should never have any behavioral consequences(*) other than changing the default value in the dropdown in the hex editor and other defaulted things.

(* Some cores, such as WaterboxCore, link the default preferred domain and the underlying representation, so there changing the `MemoryDomainFlags` will change both the preferred viewing and the behavior, but that's an implementation detail and just reflects the fact that the underlying storage and the preferred viewing are the same.  If you changed just the `EndianType` line of `WaterboxMemoryDomain`, they should still behave the same.)
