### ISSUE TITLE
Gambatte memory corruption bug

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3519]
To reproduce:
Create a savestate while in GB mode
Switch to SGB mode
Load that savestate in GB mode. The core memory gets corrupted.
If the game supports SGB functions, hard reset the game (don't reboot core).
You can't do it vice versa, because this will crash BizHawk.

**Comment by getCursorsExe** [comment]
I think I will call this "SGB in GBC".

**Comment by CasualPokePlayer** [comment]
Don't even know what you mean by ""memory corruption"", it should just crash soon after as SGB sound/border functions should stop working.

**Comment by CasualPokePlayer** [comment]
No ""memory corruption"" ever occurs here. If you load in a GB state in SGB mode, it largely ends up working (although side effects occur due to the sudden system shift, like everything is noticably black as there aren't any SGB palettes loaded now since of course a GB state has those blank, so you don't see anything until you hard reset and they (eventually) get set by the game).

If you do it vice versa, you just get this soon after (it's not related to hard reset at all so I'm not
![image](https://user-images.githubusercontent.com/50538166/212495973-e876aacd-3bee-4214-8d3d-d3ab9de5e05f.png)
(as you shifted it back internally to GB mode, so SGB specific functions explicitly fail). This is intentional behavior.

I'm going to close this as no actual ""memory corruption"" bug occurs, the core just gets into a weird state due to the user mismanaging states. Changing sync settings like this and loading states should just be expected not to work exactly sometimes.

**Comment by getCursorsExe** [comment]
You can't make controller inputs in this state.
