### ISSUE TITLE
MelonDS: screen rotate doesn't work correctly with window size 2x and higher and "Maintain aspect ratio" set

### ISSUE THREAD

**Issue by webbedspace** [TASEmulators/BizHawk#3534]
### Summary
When MelonDS's Rotation setting is set to Rotate270 or some similar value, the screens are rotated. However, when BizHawk is windowed and in 2x window size or higher, the screen space is resized as if it was not rotated, resulting in a distorted screen.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Set MelonDS's Rotation setting to Rotate270
2. Change window size to 2x
3. In Display, check "Maintain aspect ratio"

### Example
![image](https://user-images.githubusercontent.com/83939/214308589-0caf3f0e-6751-48d8-99f8-1772a4471059.png)
![image](https://user-images.githubusercontent.com/83939/214309415-3987c796-5c1b-4fdb-8d27-ce8e6ab6553d.png)

### Host env.
- BizHawk dev build at b11bb4f; Win10;

**Comment by webbedspace** [comment]
![image](https://user-images.githubusercontent.com/83939/214367990-849bf21b-584e-4ee9-b100-c01b1536c4ec.png)
![image](https://user-images.githubusercontent.com/83939/214368029-45b6a2da-f70d-417d-9274-75ce23781397.png)
Here's what my settings look like.

**Comment by CasualPokePlayer** [comment]
The issue here is caused by the `Use 1:1 pixel size` being selected rather than the `Use system's recommendation` (default) setting.
The issue is simple:
https://github.com/TASEmulators/BizHawk/blob/e2a36c7242cdc7497efa61d18b6afda799586f66/src/BizHawk.Client.Common/DisplayManager/DisplayManagerBase.cs#L811-L841
Normally vw/vh are set from the sz created with the fCoreScreenControl (DS specific thing currently really), but then these get overwritten if you are "fixing" the aspect ratio (and are not just using the system recommendation). This is probably simple enough to "fix".

**Comment by CasualPokePlayer** [comment]
This ended up getting fixed when the screen layout handling was refactored.
