### ISSUE TITLE
QuickNES savestate issue

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3568]
Possible in Super Mario Bros 3
These cheat codes must be used (or you won't be able to enter the level):
OXKIPZOS
APKZALAZ
KKKZSPIU
ESKKKTEY
Load this savestate:
[SUPER MARIO BROS 3 QUICKNES SAVESTATE ISSUE.zip](https://github.com/TASEmulators/BizHawk/files/10831901/SUPER.MARIO.BROS.3.QUICKNES.SAVESTATE.ISSUE.zip)
Press A, then rewind after the glitch level tries to load
Savestate issue should happen. You can disable the codes if you want, as this won't make any difference.

**Comment by getCursorsExe** [comment]
This fact is very weird, because there is absolutely no other point in the game that does this.

**Comment by getCursorsExe** [comment]
Alternatively you can use this one if you don't want to use cheats:
[SUPER MARIO BROS 3 QUICKNES SAVESTATE ISSUE 2.zip](https://github.com/TASEmulators/BizHawk/files/10870184/SUPER.MARIO.BROS.3.QUICKNES.SAVESTATE.ISSUE.2.zip)

**Comment by nattthebear** [comment]
> This fact is very weird and embarassing, because there is absolutely no other point in the game that does this. This means something (that can affect the game, of course) is not stored in QuickNES's savestate box.

Agreed, this is indicative of a real savestate issue in the core.  But it's not weird; most if not all cores have significant savestate issues before we start fixing them up.

The core could be waterboxed; I think we never did this because it's supposed to be a fast core, and waterbox has some overhead.  If you want best accuracy and best determinism, there's already an alternative core for that.

**Comment by Morilli** [comment]
Is this still relevant with the current quick(er)NES core in recent dev builds?
