### ISSUE TITLE
TurboNyma crash

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3594]
Writing any byte to address 0x0000 in System Bus often causes BizHawk to crash immediately. This does not occur in HyperNyma.
```
Program „[11424] EmuHawk.exe” zakończył działanie z kodem 2147483651 (0x80000003).
```
Wait, what? There's no stacktrace!?

**Comment by YoshiRulz** [comment]
CNR at 35f1e6b58b.

**Comment by CasualPokePlayer** [comment]
The crash doesn't seem to be consistent, and checking the code I would doubt it would occur for every game. Reproduced using `City Hunter (J) SHA1:8265CB33901609EC1CF156B8E0C7FC3884BC1ACD`. I don't get much useful output from GDB with a debug build, it eventually just crashes at "unimplemented syscall NR_TKILL"... which means exit was called somewhere?

**Comment by CasualPokePlayer** [comment]
OK, the crash does not occur right after the write per se, but rather possibly on internal core frame advance. The issue is rather simple: the core [fails this assert](https://github.com/TASEmulators/mednafen/blob/ddf225cf63b7b355cb2ac7772450cf473f4b53ac/src/pce/pce.cpp#L860), as certain writes can decrease the internal core timestamp, which is bad! This won't happen for reads due to [PCE_InDebug being checked](https://github.com/TASEmulators/mednafen/blob/ddf225cf63b7b355cb2ac7772450cf473f4b53ac/src/pce/pce.cpp#L135), but this check is just not present for writes. Ultimately, I'd say it's upstream's bug (this would also affect their own debugger), this should be reported to them, and perhaps for the time being we should just disable writing to the system buses for our fork.

**Comment by CasualPokePlayer** [comment]
Testing upstream actually, it doesn't appear to actually affect their release builds, I would assume that's just due to them actually having asserts no-op'd in release builds.
