### ISSUE TITLE
MelonDS low fps on NSMB Map

### ISSUE THREAD

**Issue by Danik2343** [TASEmulators/BizHawk#3604]
In NSMB Map:47 fps
In Main Menu Game:60 fps
Core:melonDS

**Comment by CasualPokePlayer** [comment]
This is expected, the NSMB map is rather intensive, more than you'd expect. It's better when in an actual level. You may want to try out the latest dev builds too, which have some minor performance improvements.

Otherwise only way currently is to just get a better PC (my own laptop from 2018 can easily run the NSMB map at full speed).
