### ISSUE TITLE
[Ares] loading state on title screen softlocks

### ISSUE THREAD

**Issue by InfamousKnight** [TASEmulators/BizHawk#3605]
In San Francisco Rush 2049 (USA), if you make a save state on the title screen where you press start,  then load the save state, audio will stop and no further input can be made.

Version used: 02caa5fc

**Comment by CasualPokePlayer** [comment]
This is odd, from what I could tell this is occuring due to the current behavior of resetting the recompiler whenever a state is loaded, which forces it to re-emit blocks of code. Now, assuming invalidation is occuring correctly, this is no problem. Except, it does appear to be a problem. If I prevent the recompiler resetting (and make the invisible blocks of memory all not invisible) it works fine. I don't want to do that however, as that at least means bring in over 16MB of possibly savestated memory, plus more for the executable memory buffer (which I could shrink from 128MB to something more reasonable like I did before, but that seems unneeded if it can be invisible).

**Comment by CasualPokePlayer** [comment]
"fixed" by 6ea7fd04d886233acaaf6eecde5426bb017d7215, I don't like it, but these issues ultimately stem from upstream being sloppy with invalidation. Once that is fixed this could likely be undone.

**Comment by InfamousKnight** [comment]
There is a workaround this issue, you can use rewind. So if a taser is trying to find the earliest frame start can be processed to advance to next screen, the taser would have to go back before the title screen appears to try another frame. Not very fun

**Comment by CasualPokePlayer** [comment]
Rewind *is* savestates, and suffers the same exact issues as I laid out.
