### ISSUE TITLE
pcehawk fix!

### ISSUE THREAD

**Issue by ghost** [TASEmulators/BizHawk#3611]
Im a idiot

**Comment by Shinobi-87** [comment]
didnt think so just mentioned since the core is still there.


I prefer nyma to be honest.

**Comment by SourMesen** [comment]
Just to clarify, Mesen's PCE emulation isn't based on PCEHawk in general, except for the SCSI/ADPCM emulation for the CD-ROM which are originally based off PCEHawk's code (with some modifications/fixes over time). This is why I have PCEHawk mentioned in the about window (which might have caused some confusion here?).

Either way, fixing this in PCEHawk is probably not too hard, assuming the cause is identical (though I realize the core is not being updated anymore)
