### ISSUE TITLE
[BSNESv115+] "No PPU sprite limit" option doesn't seem to work

### ISSUE THREAD

**Issue by Sonia-7** [TASEmulators/BizHawk#3643]
Whether that option is checked or not makes no difference. A good way to verify if it's working is by looking at a FF6/3 early game cutscene. It's the one where Kefka sends two magitek soldiers after Terra's party in the desert. If you use magic in that battle, Edgar and Locke will begin talking, and at some point their sprites will be hidden behind the menu window. However, if no sprite limit is checked, their bodies will appear exposed, like this:

![Sprite limit off](https://user-images.githubusercontent.com/24638400/233758223-80a27dc1-2091-44d0-8c6a-9ff146115d2b.png)

Whereas normally (sprite limit enabled) it shows like this:

![Sprite limit on](https://user-images.githubusercontent.com/24638400/233758232-22354ec9-6f7b-4a45-a782-3ea6e8a23a77.png)

However, even with the box checked bizhawk still shows the correct behavior instead of the glitch. The bugged screenshot was captured with standalone bsnes v115. 

To help making things faster, I made a saveram and savestate:
[FF6 savefiles.zip](https://github.com/TASEmulators/BizHawk/files/11300123/FF6.savefiles.zip)

The saveram is near the cutscene. Enter the castle and talk to Locke to start the event. While the savestate loads the cutscene instantly. Just keep pressing A to scroll through dialogue.

Tested with the clean No Intro dump: "Final Fantasy III (USA).sfc" 
Bizhawk version: 2.9 stable release.

**Comment by getCursorsExe** [comment]
I think this is expected, the game seems to place an absurd of sprites off-screen to hide some other sprites.

**Comment by CasualPokePlayer** [comment]
![image](https://user-images.githubusercontent.com/50538166/233781484-36218d02-b665-4c49-8179-6c43713ae703.png)
It does appear to "work" if you change settings in between power on and the event.

I suspect the issue is due to [this function](https://github.com/TASEmulators/BizHawk/blob/f7b83be5ab36398e4b0de1c7a644b3f48ae3f99d/waterbox/bsnescore/bsnes/target-bsnescore/bsnescore.cpp#L280-L287) not actually setting the internal config options, leading to its effects being overriden on [the core's power function](https://github.com/TASEmulators/BizHawk/blob/f7b83be5ab36398e4b0de1c7a644b3f48ae3f99d/waterbox/bsnescore/bsnes/sfc/ppu-fast/ppu.cpp#L202-L203), and said function also running after putting the initial settings.
