### ISSUE TITLE
Remove "new lua" option

### ISSUE THREAD

**Issue by Berserker66** [TASEmulators/BizHawk#3650]
### Summary
We probably have over 100 cases of people accidentally using new lua script when they mean to click open lua script by now.

The easy solution would be to just remove the new lua option, as someone who would write a lua script almost certainly knows how to make a new text file and make it a lua.
Alternatively, one could make the empty-ish lua that gets created aggressively print that it is a fresh empty lua script created by bizhawk.

**Comment by YoshiRulz** [comment]
Obviously we can only speculate how many people misclick the button, telemetry can't tell you that, but it seems unlikely when the new and open buttons use conventional icons.

> Alternatively, one could make the empty-ish lua that gets created aggressively print that it is a fresh empty lua script created by bizhawk.

I did something like that for 2.9: https://github.com/TASEmulators/BizHawk/commit/380e459becfbd33c66c4bca58a243153ce9483d7

**Comment by Berserker66** [comment]
well I can give you a discord invite link where you can search for "new lua" and find 45 cases of people falling into this trap.

**Comment by CasualPokePlayer** [comment]
"New Lua Script" creates a new lua script (indicated with a blank paper), and "Open Script" opens a new script (indicated by a folder and an arrow). I'm not sure how that is confusing other than people clicking the top left icon without really checking it. This is even standard iconography used in other applications.

I myself use this option quite often as it's a very convenient way to put a new lua script file in the lua folder with the basic loop template. And since 2.9, it will explicitly tell you that the created file is a template. I would suspect it's the same for many users. We are not going to remove this option.

If the comments pointing out the created file is a template are not enough, then do you have any proposal on how to indicate better to users what does what? As clearly, these users are not understanding the icongraphy used (despite this being standard icongraphy and really its usage makes sense as far as I can see), and these users are not reading out the tooltips that come when you hover over the icons.

**Comment by Yoshi348** [comment]
I think the thing that is happening is that snes9x-rr makes you click an option labeled "New Lua Script Window" to do lua stuff. This project ends up transferring a lot of people who uses and prefer snes9x for lua enabled snes stuff to bizhawk for non-snes stuff. Similiar wording with one very key difference.

Demanding the removal of a feature people actually use seems pretty silly. Bizhawk is using the standard templating for this. There is, however, one thing that it does that is NOT normal with "new file" options, and that is forcing you to immediately name and save your new file before anything happens. This is not what such an option would do in something like Word, and probably a lot of people assume they're opening a file when immediately presented with the file selector.

Is there a reason you immediately save?

**Comment by CasualPokePlayer** [comment]
How do you open a non-existing file?

**Comment by Yoshi348** [comment]
I just mean that when you choose new file in most text editors, it exists only in memory until you press save and give it a name. It usually doesn't make you create the file somewhere on disk before giving you the new blank file. (At least from how things tend to work in Windows in non-programming contexts, which is what I and many others would be familiar with.)

**Comment by CasualPokePlayer** [comment]
Yes, because they're text editors themselves. BizHawk is not a text editor.

**Comment by Yoshi348** [comment]
Oh, okay, now I'm seeing what's going on. I feel kinda silly commenting without actually really using this stuff.

**Comment by YoshiRulz** [comment]
As I suspected, Archipelago's docs are overcomplicating the process of loading a Lua script. With drag+drop, there are fewer mistakes that someone could possibly make, which is obviously desirable when writing docs for the users who need more hand-holding. I'll be submitting a PR with that and some other changes.

**Comment by Berserker66** [comment]
Our userbase has been reporting gripes with this for a while, the straw that broke the camels back that lead to this issue was a livestream https://www.twitch.tv/videos/1808045198 where roughly 20 minutes were spent troubleshooting. Something went wrong somewhere, causing the streamers to restart their emulators, still not sure what that was. In doing so one of them accidentally used new lua script when quickly setting up again, causing a spiral of problems to occur afterwards.

**Comment by CasualPokePlayer** [comment]
> I just tried to walk though the steps again to recreate my thought process, but I now see a clear warning that I'm about to overwrite the selected file. I don't know if that behavior has changed recently or if I was just dumb and clicked through anyway. Either way, that addresses the main gripe I thought I had about there being no overwrite warning.

That warning is from Windows, since you're ultimately in Windows' "Save As..." dialog (if it didn't warn you, that'd be the fault of the OS, not us).

> I think changing the name, icon, and maybe position in the menu could cut down on user error. I think having the word 'File' in there somewhere would've cleared up my faulty assumption about how things worked.

The icon is a blank piece of paper, indicating a new *blank* lua script. This is a standard icon, and isn't going to be changed.
The positioning is also standard, new comes before open.

I'm not sure having "file" here is going to be any better. You weren't paying attention enough to the overwrite file dialog, so I would have doubts you'd pay attention enough to notice "file" being present or not. You also just way overcomplicated the logic of how it works, you give it a lua script file and BizHawk does all it needs to it internally (and kind of "wrapping" logic is not your job).

It's even more simpler with Yoshi mentioning drag+drop, to open a lua script you can just drag and drop the lua script directly on the BizHawk window, and it will automatically open the lua console with the lua script opened and running. You do not need to open the lua console yourself at all.

**Comment by kbranch** [comment]
I agree that the current setup is a standard UI convention and is logical from the point of view of somebody who understands how the program works. I just think that it can be misunderstood by new users because that standard is used in an unusual context - as mentioned earlier, BizHawk is not an editor.

The behavior of the 'New' button is also somewhat unexpected, at least to me. I'm not sure I've seen 'New' open a file dialog and overwrite the contents of that file before. Again, I get why it's like that, and I'm not trying to bash anybody, but it could contribute to user error.

Better docs are always good, but an awful lot of users are never going to see them. Being able to drag and drop the script is neat and a good thing to mention in the Archipelago guide, but I didn't even consider that until hearing it here.
