### ISSUE TITLE
[F.Rq.] Expose Blargg NTSC filter in Genplus-gx

### ISSUE THREAD

**Issue by ghost** [TASEmulators/BizHawk#3672]
Expose blarrg ntsc filter setting under core settings for gens plus gx.

**Comment by YoshiRulz** [comment]
This looks like a post-processing filter (shader), which is a frontend concern. You can load custom shaders under `Config` > `Display...`, though not all shaders will work. Blargg's definitely won't work because it's not really a shader—it's a library which is compiled in, and runs on the CPU according to [the readme here](https://github.com/ekeeke/Genesis-Plus-GX/tree/master/core/ntsc#readme).

**Comment by 007mesen** [comment]
The core has this built in tho but ok
