### ISSUE TITLE
Make the Admin privs warning less useless for the user

### ISSUE THREAD

**Issue by ElektroStudios** [TASEmulators/BizHawk#3835]
### Summary

This is not a bug but I consider it a design issue.

The emulator warns about administrator privileges in a way that is totally invasive, repetitive, and unnecessarily annoying, without the ability (apparently) to allow the user to disable the prompt.

That warning will appear for any user under an account with admin privileges, and of course if the user (like me) is just using the built-in Administrator account for his personal computer. (there is no reasonable reason why I should be using an account with less privileges, and nor any reasonable reason why I should restrict privileges to the EmuHawk.exe process)
​
I expect a way (maybe an option in the emulator settings) to disable this warning every time that I run the emulator.

I'm not sure whether this can be disabled through the emulator options, but I didn't found anything to disable it. Please excuse me if the solution to disable this warning is already known, but I didn't found it.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."

Not needed.

### Output

![WinSnap 02](https://github.com/TASEmulators/BizHawk/assets/13082613/da089c31-1b0f-441d-be60-6aa0461f58b7)

Also... what means "This is a bad idea"?, In addition to being repetitive, the message completely lacks useful information that the user can value accordingly, it is just an annoying and imprecise (useless) message.

Anyways, If I try to figure out why possible reasons that can be a "bad idea", I have no intention of loading rom files with exploitable security errors or anything similar that could affect me.

### Host env.

BizHawk v2.9.1
Windows 10.0.19045.2006. 

Using the built-in Administrator account, you know:

>     Using a command prompt
>     
>     To activate: "net user administrator /active:yes"
>     To deactivate: "net user administrator /active:no"

**Comment by YoshiRulz** [comment]
Power users can disable the warning by setting `"SkipOutdatedOsCheck": 1` in `config.ini`.

**Comment by vadosnaprimer** [comment]
>  In addition to being repetitive, the message **completely lacks useful information** that the user can value accordingly, it is just an annoying and imprecise (useless) message.

**Comment by CasualPokePlayer** [comment]
> That warning will appear for any user under an account with admin privileges

This is wrong, Windows 10/11 (which are the only ones we check this) do not do this. This *was* the case for Windows 7/8/8.1 (and probably older windows) due to how UAC worked then. However, Windows 10/11 will not give an application admin perms even if you are an admin, unless the application is explicitly marked for requiring admin perms (we don't do this), or the user explicitly runs as admin (right click -> Run as Administrator).

The only case I've seen users actually getting this is so far they have a registry edit which disables the UAC entirely (google "disable uac windows 10 registry"). This itself is dangerous, as this actually means standard users have Administrator perms rather than being restricted to Administrator users.

Turning this back on however has to be done with caution, as due to the mentioned dangerous situation with standard users having Administrator permissions, this means if you turn UAC back on blindly, you could end up being the only user and without Administrator perms, requring a lot of bs to activate the default Administrator account and get back Administrator perms.

**Comment by YoshiRulz** [comment]
Sorry about the confusion. There's your toggle and elaboration, as requested.

**Comment by CasualPokePlayer** [comment]
https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-account-control-admin-approval-mode-for-the-built-in-administrator-account

Apparently, the built-in Administrator account actually has different rules here. While typical Administrator accounts (i.e. not the built-in one) will normally (assuming you don't do the registry edit) only launch applications under standard user permissions and require explicit elevation, the built-in Administrator has a separate policy on whether this is done or not. And by default, it will launch any application with Administrator permissions, unlike standard Administrator accounts.

**Comment by YoshiRulz** [comment]
[dev builds](https://github.com/TASEmulators/BizHawk#development-builds)

**Comment by valentinovitez** [comment]
Hey folks. I have the same issue and haven't found a solution. I'm using an administrator account on this pc and am supper happy with BizHawk, but there is that message every time I start the programme. 

Not only is it a bit annoying but it also breaks the immersion in my otherwise full-on-console experience on my pc. 

Is there a way of fixing this easily ? I was hopping I could just edit a a file in notepad turn a 1 to 0 or a true to false and no longer see this message.

I am willing to learn, even read a few pages on finding a solution to this annoying issue, it is that terrible.

Someone please help. A basic upload of a file that I can just copy paste to fix this issue would also be great. Well . . . any solution would be great. As long as instructions are understandable to someone who has only a basic background in programming, before dropping out 😁

I love BizHawk but I hate this administrator privilages message. Help please.

**Comment by YoshiRulz** [comment]
Click the link in my comment (the one above yours).

**Comment by CasualPokePlayer** [comment]
> https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-account-control-admin-approval-mode-for-the-built-in-administrator-account
> 
> Apparently, the built-in Administrator account actually has different rules here. While typical Administrator accounts (i.e. not the built-in one) will normally (assuming you don't do the registry edit) only launch applications under standard user permissions and require explicit elevation, the built-in Administrator has a separate policy on whether this is done or not. And by default, it will launch any application with Administrator permissions, unlike standard Administrator accounts.
> 
> You should be able to enable "Admin Approval Mode" for the built-in Administrator account in the Local Security Policy settings ![image](https://private-user-images.githubusercontent.com/50538166/291054521-03e7bd4b-b928-42f7-a8bf-7d6dc2f4751a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODk4MDksIm5iZiI6MTcwNDE4OTUwOSwicGF0aCI6Ii81MDUzODE2Ni8yOTEwNTQ1MjEtMDNlN2JkNGItYjkyOC00MmY3LWE4YmYtN2Q2ZGMyZjQ3NTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA5NTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MmM3OGNkMWFjMDk0NTg5MDg0NTM0ZmIzNDZlMTlhOTYwZDc1NTAzYzVmZDJhNGFhMGI2YjM3NTM1OTQ2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nep9LPUxbXJZjj-LGKpa4-qxmergzNsNj4sTPZJ-fpQ)

Alternatively, if you're using the "builtin" Administrator account, just enable Admin Approval Mode in Local Security Policy.

**Comment by valentinovitez** [comment]
Yoshi you are the king. You made me read and I am super grateful to you for that. 

It looks like that up to today I didn't know how to use Github but today I learned. To us civilians words like " artefacts" mean the holy grale or the Excalibur but in the dev-lingo they mean something else. So that was somewhat confusing, words that mean something else.

Well anyway, I did some reading and BizHawk works like a charm now. Very grateful to you folks. And you thought me how to download GitHub stuff. Hehe, nice tutorial.

Thank ya

**Comment by Edvarcht** [comment]
> > There's your toggle and elaboration, as requested.
> 
> Thank you every body for the support.
> 
> But one last thing, please, @YoshiRulz can you tell me ~the name of the new setting in the config.ini?, I got lost in the conversation.~
> 
> Nevermind, I found it: [0e084ea](https://github.com/TASEmulators/BizHawk/commit/0e084eaefd84f49abb14a8d24e1310f923e406df)
> 
> Then now I should wait for a new stable release, or maybe I can find some kind of dev/nightly release?.
> 
> **EDIT:** Anyways, the source code for the master branch compiles like a charm. I thought it would be full of missing external emulation-retaled dependencies hard to figure out...

Hey what's up, new here and totally program/code novice. Would you be so kind to tell me what do I have to do with that code on the link you provided? And which part, because I can see a lot. Thanks in advance!

**Comment by YoshiRulz** [comment]
You don't have to touch the code. Just grab a [dev build](https://github.com/TASEmulators/BizHawk#development-builds), and once you've opened and closed it, flip `SkipSuperuserPrivsCheck` in the config.

**Comment by Edvarcht** [comment]
> You don't have to touch the code. Just grab a [dev build](https://github.com/TASEmulators/BizHawk#development-builds), and once you've opened and closed it, flip `SkipSuperuserPrivsCheck` in the config.

Dang, it was very easy. Thanks a lot! Cheers.

**Comment by rev3rbjunkie** [comment]
Hi there! I'm dumber than everyone else here and don't know what yoshi means by "flip" skipSuperuserPrivsCheck in the config. Do you mean open the config file and edit the text to read true instead of false next to skipSuperuserPrivsCheck? or is this an actual setting I can enable or disable in the user interface? and if its just editing the config file do i then replace my old config file in my normal install with this new config? Or am i stuck using the dev build?

**Comment by YoshiRulz** [comment]
I'm going to suggest that, if you're not the kind of person who can decipher and act on those instructions, you won't have a good reason to be running programs as admin. So don't do that. But yes, you need to open `config.ini`, find the line reading
```
"SkipSuperuserPrivsCheck": false,
```
and change it to
```
"SkipSuperuserPrivsCheck": true,
```

Seriously though, stop running programs as admin.
