### ISSUE TITLE
Gameboy Movie to SGB

### ISSUE THREAD

**Issue by Danik2343** [TASEmulators/BizHawk#3838]
Is it possible to convert GameBoy Movie to Super GameBoy Movie? (Gambatte,BSNES, BSNESv115+)

**Comment by Danik2343** [comment]
And should we expect this feature in the future? I know about the emulation of different kernels, most likely it will not be possible to implement this function.

**Comment by YoshiRulz** [comment]
Copy the input log into a blank movie.

I don't think this is something we should implement because it can't be used outside of this one circumstance.

**Comment by CasualPokePlayer** [comment]
Frankly too, you'd need to end up doing manual resyncing anyways. And especially for LLE cores such as BSNES/BSNESv115+ due to the way SGB input is handled, also some inputs is impossible to represent on the SGB (Up+Down and Left+Right is prohibited by the SGB software and HLE emulators mimic this restriction).
