### ISSUE TITLE
[Question] How Are Timings for the Platforms Obtained and or Determined?

### ISSUE THREAD

**Issue by DeadSkullzJr** [TASEmulators/BizHawk#3926]
Hello, I come with a simple question. How does one get exact frame rate timings from certain platforms? I was looking online and reading up on all the strange timings that certain platforms, game consoles and computers to be more specific, seem to have, initially a lot of folks say that things are either 60 frames (NTSC) or 50 frames (PAL), but clearly it isn't that simple. I encountered the page below and was wondering how these were calculated or obtained, and if there was a way I could find out myself for some of the systems that I own, especially those not listed in the web page below. I also have to ask, why do some of the platforms have so many duplicate timing entries, seems rather inconsistent that a console would have multiple timings rather than a set timing like others tend to have.

Web page in question:
[https://tasvideos.org/PlatformFramerates](url)

**Comment by YoshiRulz** [comment]
The TASVideos.org list contains every value ever used in a publication.
For our list, check [the blame](https://github.com/TASEmulators/BizHawk/blame/master/src/BizHawk.Client.Common/movie/PlatformFrameRates.cs). For the most part, they're sourced from people who've reverse-engineered the console.

**Comment by CasualPokePlayer** [comment]
TASVideos' PlatformFramerates just includes any ""framerate"" included for any submitted movie. Some might be from ancient emulators (not accurate at all), or possibly just mucked values to handle variable framerate consoles (due to timing on TASVideos internally strictly being derived from framerate and framecount, so framerate may be mucked in order to make it have the right time with a given framecount of a movie, in this case the correct final movie time derived from some cycle count in the movie).

**Comment by Randomno** [comment]
> How Are Timings for the Platforms Obtained and or Determined?

Generally, [CPU clock speed] divided by [cycles per frame]. So the SNES runs at 21477272 Hz and outputs a frame every 357368 cycles. But then there are other quirks to account for, like how every other frame, one scanline takes 4 cycles fewer, which averages out to 2 cycles per frame. So the "official" framerate is 21477272 / 357366.

https://wiki.superfamicom.org/timing
