### ISSUE TITLE
Hang when using "Hide Lag Frames" with Ares64

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#3972]
To repro:
1. Open SM64 in Ares64
1. Launch TAStudio, creating a new project
1. Emulate through frame ~250, pause, and seek to start
1. Set `Settings` > `Hide Lag Frames` to 1
1. Unpause, and at frame 160 observe a hang (both windows stop updating and no longer respond to input, though my WM doesn't flag them as unresponsive)

Affects:
- NixHawk 2.9.1 on NixOS
- local build of 15125ec11fcbff1563f1f8e79dc0bfde98ddcdec on NixOS; reproducible in Debug config but sadly no stacktrace

**Comment by Morilli** [comment]
Important note: This requires `Follow Cursor` to be active, otherwise it doesn't hang and just doesn't update TAStudio correctly (at least visually).

It gets stuck in this do while loop:
https://github.com/TASEmulators/BizHawk/blob/dfe8b1308c38057419067aeb39accea74b84a55b/src/BizHawk.Client.EmuHawk/CustomControls/InputRoll/InputRoll.cs#L802-L816
`lastVisible` cycles between `160` and `162`, range is `0 - 0` and `value` is 161.

**Comment by YoshiRulz** [comment]
Still jank but doesn't hang.
