### ISSUE TITLE
[Amiga core] Disk switching not recorded properly / playback desynch at disk switch

### ISSUE THREAD

**Issue by ScHlAuChii** [TASEmulators/BizHawk#3995]
### Summary
Switching disks is not recorded properly

### Repro
1. Pick a multi disk game (Aladdin - 3 disks in this example)
2. Create a XML with the Multi DIsk Bundler 
3. Record a movie and switch the disks when its requested - all works fine.
4. Play back the movie and it desynchs as the disk switching isnt working.

### Host env.
Recent Dev build

**Comment by vadosnaprimer** [comment]
Game info

cb37d0ffe39cb93843fd5585241ddf36ea13ea19  "Aladdin (AGA)_Disk1.adf"
a3997381c4e82d97c941adbdc4c5d5e94b7e5019  "Aladdin (AGA)_Disk2.adf"
089849f727eda32be724e0a5ff6e5714f5b46951  "Aladdin (AGA)_Disk3.adf"

[Movie file and xml bundle](https://github.com/user-attachments/files/16571681/Aladdin.zip)

**Comment by CasualPokePlayer** [comment]
https://github.com/TASEmulators/BizHawk/blob/9825ac6db623aa927662662ef2a639eb0e70c069/src/BizHawk.Emulation.Cores/Computers/Amiga/PUAE.cs#L28-L29
Likely fault of these variables not included in savestates.

**Comment by CasualPokePlayer** [comment]
Check if 54fd290107d7b2a79d8033f0f289dd8d1bd190f3 fixes this

**Comment by SergioMartin86** [comment]
> Check if [54fd290](https://github.com/TASEmulators/BizHawk/commit/54fd290107d7b2a79d8033f0f289dd8d1bd190f3) fixes this

The commit fixed the issue with disk swapping, so now I can play games that require changing disks on the fly.  So the change from disk 1 to disk 2 is effective now.

However, the original issue reported here remains: if you use TASStudio and go back to the frame just before the swapping and swap again, you are going to get disk 3 (instead of 2). Seems like the currently _selected_ disk id (as opposed to the _loaded_ one) is still not stored in the state.
