### ISSUE TITLE
RetroAchievements doesn't detect DS/DSi games

### ISSUE THREAD

**Issue by yoshiweegee** [TASEmulators/BizHawk#3996]
### Summary
Pretty much as the title says: no DS/DSi game is ever detected. The Game Info window never has information about a DS/DSi game, and the Achievements List window remains empty.

### Repro
1. Log in to RetroAchievements
2. Open a compatible DS/DSi game (such as Mario & Luigi: Bowser's Inside Story)
3. Open the Game Info window and observe that the game is not detected
4. Open the Achievements List window and observe that it is empty

### Host env.
BizHawk 2.9.1 (x64; EmuHawkMono.sh); Linux Mint Cinnamon 21.3 (Ubuntu 22.04); AMD Ryzen 5 7600;NVIDIA GeForce RTX 4070

![image](https://github.com/user-attachments/assets/1a102d60-592a-4ebb-99c5-e877b3b73e84)

**Comment by CasualPokePlayer** [comment]
Last I checked DS/DSi games worked fine.

The screenshot you provided also shows the actual issue: you are not using the correct version of the game. [As their site lists](https://retroachievements.org/game/5323/hashes), you need the *European* version of this game. (in general, RetroAchievements policy is to use European versions of games for handhelds due to multi-language support)

**Comment by yoshiweegee** [comment]
Thank you for directing me to that page. I was looking for something like it before, but couldn't find it.
