### ISSUE TITLE
2.10-rc1 has forced ordering for gui text draw, causing unpreventable UI issues

### ISSUE THREAD

**Issue by UTDZac** [TASEmulators/BizHawk#4036]
### Summary
We have a few Lua scripts to run alongside Pokémon games for GBA (mGBA core) and NDS (melonDS core).

The new 2.10-rc1 build has changed core functionality of some critical `gui` text draw functions that we use to create a tracker UI. The 2.10-rc1 forces texts to be drawn *after* everything else, regardless of the order specified within any Lua scripts. This causes multiple undesirable outcomes within our UI, as we no longer have control over being able to build and display proper UI elements as before. (To note: in some cases we can resolve this by removing unnecessary gui draws or adding conditions, but with many of our UI elements this is not a possible fix due to the enforced display order.)

Here is the notable change from `GuiLuaLibrary.cs` (one of a few locations):

> [LuaMethod("drawString", "... Note that all text drawing occurs after all other drawing occurs (e.g. after gui.drawRectangle() regardless of call order).")]

And here is how it affects our client drawn UI: 

> _(See "Fig. 1" from the Screenshots section at the bottom)_

### Repro
1. Draw some text "Foo Bar" on a screen at position (5, 5)
2. Draw a filled-rectangle completely enveloping the above text (0, 0, 100, 100)
3. Draw some text within this rectangle, near the original text (5, 5) or (6, 6)

```
gui.drawText(5, 5, "Foo Bar", 0xFF0000FF) -- blue font
gui.drawRectangle(0, 0, 100, 100, 0xFF000000, 0xFF000000) -- black background
gui.drawText(6, 6, "Foo Bar", 0xFFFFFF00) -- yellow font
```

### Output
![image](https://github.com/user-attachments/assets/dfddf02c-2d06-413c-a40b-3730cbeebf41)

### Host env.
- BizHawk 2.10-rc1; Win10 Home 22H2; Intel/NVIDIA

### Screenshots

Fig. 1
![image](https://github.com/user-attachments/assets/34759446-8503-43f5-95eb-b5d449086a62)

Fig. 2
![image](https://github.com/user-attachments/assets/cae53ec4-148e-4981-ab17-54ca28754243)

**Comment by CasualPokePlayer** [comment]
This is somewhat an irreconcilable change here. The gui API was revamped to actually be hardware accelerated (previously it would all be software rendered, which was particularly slow if you had a ton of primitives drawn). However, gui.drawText is not able to actually be hardware rendered, instead it has to be software rendered still (since it has to go through the complex GDI text drawing with system fonts with all the bells and whistles options that comes with), then performed last to draw over the hardware accelerated gui API surface (since the actual drawing onto the surface has to be deferred until the end due to the hardware acceleration nature).

**Comment by CasualPokePlayer** [comment]
Relooking at the new code, and I think I can end up making it work. The code would need to still technically defer the actual string drawing to the end, but it could end up doing so between other gui calls.

However, doing this would end up having some severe performance implications, since it is effectively draw string onto software bitmap, upload bitmap to GPU texture, draw GPU texture over current gui surface, for every single string draw operation, rather than all at once. I think it might be possible to make this performance consideration relatively minimal though, as long as some code is placed in to attempt to clump together string draw calls (i.e. whenever there are successive string draw calls with no other kinds of gui draw calls in-between, the ideal case).

**Comment by UTDZac** [comment]
Awesome. Thank you so much for looking into this and fixing it up. I understand the complexity behind the new performance changes, so I really appreciate being able to restore this functionality.

**Comment by UTDZac** [comment]
We are doing some light testing and have only encountered one other issue with gui related script execution. I take it you'd prefer I open a new Issue for this? I haven't done so yet as we're having trouble identifying exactly what's causing it or why its happening; different results on different computers.

**Comment by YoshiRulz** [comment]
Yes, open a new issue for that thanks.

**Comment by CasualPokePlayer** [comment]
Slightly unrelatedly, I am curious, what are the performance differences you are seeing with the scripts? Are they around the same as before, worse, better?

**Comment by UTDZac** [comment]
I'm unsure of the best way to fully test performance here, but the simple thing I checked was FPS while running on Unthrottled clock speed. I can confirm the recent bugs for this issue and another were fixes in the nightly build.

### Bizhawk 2.9.1
- Running around in Pokémon Fire Red with our Tracker UI results in about 450-520 FPS
- With Log Viewer overlay UI (significantly higher quantity of gui draws) results in 420-490 FPS

### Bizhawk 2.10-rc1
- Running around: 500-560 FPS
- Log overlay: 470-510 FPS

### Bizhawk 2.10 nightly dev (commit [master@67cba14e3](https://github.com/TASEmulators/BizHawk/commit/67cba14e38de721fb5b483ad1fce1f33e93e4923))
- Running around: 480-540 FPS
- Log overlay: 460-520 FPS

All of these are very loose estimates, but nothing stands out as being significantly impacted.

---

Small aside: The sound effect that plays when viewing Bizhawk > About is quite loud and bypasses "Enable Master Sound", which I typically have my emulator completely muted at all times (for streaming). The sound doesn't seem to adhere to the sound slider volume, if that matters, but its quite loud.
