### ISSUE TITLE
[Bizhawk 2.10 rc1] client.SetGameExtraPadding causes stretching with NDS scaling

### ISSUE THREAD

**Issue by Brian0255** [TASEmulators/BizHawk#4039]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
For melonDS, if either OpenGL renderer is selected and the Scale Factor is set higher than 1x, client.SetGameExtraPadding will stretch the emulator screen. When using this function in Bizhawk 2.9, the emulator screen does not stretch.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Set the 3D Renderer to "OpenGL Classic" or "OpenGL Compute"
2. Set "OpenGL Scale Factor" higher than 1
3. Reboot the core and load an NDS ROM & Lua script with the following code:
```
client.SetGameExtraPadding(0, 0, 250, 0)
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.10rc1; Win11; AMD/NVIDIA

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."
### Screenshots
<img src="https://github.com/user-attachments/assets/5179ab05-dcbd-4375-aece-08f984ad44bf" width="400">

**Comment by Brian0255** [comment]
I should note, `client.SetClientExtraPadding` seems to work fine and doesn't have this problem. Perhaps I should just be using that instead?

**Comment by CasualPokePlayer** [comment]
This would be somewhat some kind of breakage due to how this is handle. client.SetGameExtraPadding goes against the "emucore" surface, which for melonDS might be *larger* than the "client" surface if you end up setting the scale factor up. The intent is to more match how emulators de facto handle internal resolution scaling, where they don't increase the window resolution. I would assume some handling here does not like this unexpected relationship.

BizHawk 2.9 does not even have melonDS's OpenGL renderer, so it's not a valid comparison here.

You might be able to workaround it (somewhat) regardless using client.SetClientExtraPadding and watching the window scale with other apis.

**Comment by CasualPokePlayer** [comment]
Note too, this issue likely also affects the Encore (3DS) core as it handles internal scaling the same way.
