### ISSUE TITLE
TAStudio Recording mode gets extremely slow for longer movies

### ISSUE THREAD

**Issue by RetroEdit** [TASEmulators/BizHawk#4058]
To be more precise, the later in the movie you are, the slower recording mode is. So if you seek to an early frame in a long TAStudio movie and turn on recording mode, recording will often be fast.

It does also seem to be affected by how long the current movie has been open in TAStudio, but later frames are slower regardless.

This doesn't affect non-recording mode playback in TAStudio or read+write mode in traditional re-recording. It applies whether or not display is enabled.

I observed with both Gambatte and mGBA, and assume it affects all other cores.

### Repro
I find it pretty easy to just take a longer movie and observe how slow recording mode is later in the movie.

I went a bit overkill and created a script to measure it more rigorously under different conditions: [measure_playback_speed.zip](https://github.com/user-attachments/files/17171423/measure_playback_speed.zip)

And from that data, I created this graph:

(for the below test, display was "absolute zero", clock unthrottled, "follow cursor" off, TAStudio autosave interval set to 0, and TAStudio minimized.)

![2 10-rc1_GB_speeds](https://github.com/user-attachments/assets/ce480caf-0e16-4a72-9931-e7b0cf93b3b8)
(edit: An alternate view of the same data reveals that the curve for recording mode is hyperbolic—that is, frame times increase linearly.)

### Host env.
- Does *not* affect BizHawk 2.3.1
- (Affects BizHawk 2.3.2; Win11, BizHawk 2.3.3, BizHawk 2.4.2; Win11)
- BizHawk 2.9.1; Win11
- BizHawk 2.10-rc1; Win11
- BizHawk 2.10 dev build at 15ff0ec; Win11
  - (Latest dev build at time of writing)

**Comment by Morilli** [comment]
Can you clarify what state the tasmovie was in when you did these tests? Mainly I'm interesting in the length of the tasmovie and whether or not states were recorded during these runs.

If you have a tasproj with 300k frames pre-recorded and are playing through them I'd expect a different result compared to recording 300k frames from start. I don't see how either of those would produce an ever-increasing frametime based on movie length, but I would still like to know for reproducing purposes.

**Comment by Morilli** [comment]
Okay I can easily reproduce this and did some basic profiling:
Playback mode:
![image](https://github.com/user-attachments/assets/c82ce32a-cb06-4977-b7f6-597b25513b41)

Recording mode:
![image](https://github.com/user-attachments/assets/b69de6e2-03a1-4154-9529-8b738e03dd77)

**Comment by RetroEdit** [comment]
> Can you clarify what state the tasmovie was in when you did these tests? Mainly I'm interesting in the length of the tasmovie and whether or not states were recorded during these runs.

Late and now irrelevant reply, but aside from the settings I mentioned, my settings were the default. I generally delete my config before doing any testing.

I can say from some earlier testing I'm pretty sure both cases had fairly similar results.

**Comment by Morilli** [comment]
Hmm I did some more testing and I can still measure a significant slowdown when using a core that generates many states and is very fast (like quickernes).

ae5d4ab160fce3708342a492abfcb5d5829f24c1 helps a lot already, but we could probably still improve this logic further. For reference, I get ~1200 fps in recording mode before ae5d4ab160fce3708342a492abfcb5d5829f24c1 and ~3200 fps after, but it's still far off from the ~6400 fps I get outside of recording mode.

The issue is very clearly the O(n) loops performed in [InvalidateNormal](https://github.com/TASEmulators/BizHawk/blob/ccb69b18a9ef715f7f32bd7cba9ef546d0ea2d71/src/BizHawk.Client.Common/movie/tasproj/ZwinderStateManager.cs#L500):
![image](https://github.com/user-attachments/assets/b850647a-f955-4949-94c9-ea3493dd2994)
