### ISSUE TITLE
[🐧] Host audio stops when MainForm dragged

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#4145]

**Comment by CasualPokePlayer** [comment]
This seems to be caused by the ResizeBegin/ResizeEnd triggering when you're moving the window, which mutes sound. This muting does make sense, as on Windows, the main thread will be "frozen" within message pumping while the resize or window move is occurring (such things are more or less considered "atomic"-esque in the view of the main thread on Windows), so new samples can't be delivered to the sound system in this state. On Linux, this doesn't appear to be the case. Probably easy enough to fix with some OSTailoredCode.IsUnixHost usage.

(As a side note, this quirk also makes the [resize window title code](https://github.com/TASEmulators/BizHawk/blob/24d549ddb84d7c257aabbd627a04616394fe7fc5/src/BizHawk.Client.EmuHawk/MainForm.cs#L1746-L1750) effectively non-functional on Windows, it only ever shows up on Linux).

**Comment by kalimag** [comment]
> (As a side note, this quirk also makes the [resize window title code](https://github.com/TASEmulators/BizHawk/blob/24d549ddb84d7c257aabbd627a04616394fe7fc5/src/BizHawk.Client.EmuHawk/MainForm.cs#L1746-L1750) effectively non-functional on Windows, it only ever shows up on Linux)

Works fine for me on Win10. It's updated from the [Resize event](https://github.com/TASEmulators/BizHawk/blob/24d549ddb84d7c257aabbd627a04616394fe7fc5/src/BizHawk.Client.EmuHawk/MainForm.cs#L530).

**Comment by CasualPokePlayer** [comment]
> Works fine for me on Win10. It's updated from the [Resize event](https://github.com/TASEmulators/BizHawk/blob/24d549ddb84d7c257aabbd627a04616394fe7fc5/src/BizHawk.Client.EmuHawk/MainForm.cs#L530).

Ah, looks like it depends on some Windows settings, one of the visual effects settings can effectively prevent it from working due to it making the Resize event happen at the end on resize completing, interestingly enough.
