### ISSUE TITLE
"for line in openedfile:lines() do" fails in 2.x

### ISSUE THREAD

**Issue by mugg91** [TASEmulators/BizHawk#995]
I explained my issue here: http://tasvideos.org/forum/viewtopic.php?p=458352#458352

If you open a file with `io.open()` and then run `for line in openedfile:lines() do` on it, it will output an error. It does not happen in the 1.x versions.

**Comment by Tastyfish** [comment]
Yeah, seems like a bug in either the version of NLua we're using, or whatever lua it's interfacing to (the project seems to contain lua51.dll _and_ KopiLua?) and for that matter also LuaInterface.dll, despite nlua being a fork of that. I actually have no idea what we're using in general for lua, other than that in theory it's supposed to work as 5.1 but file i/o is broken as heck; `f:read("*l")` also seems to be returning results with newlines, which it shouldn't, and crashes on EOF instead of returning `nil`. Here's a really nasty hackjob fix I guess...

```lua
function io.lines(filename)
	local f = io.open(filename, "r")

	local iterator = function(f, prevLine)
		local success, line = pcall(function()
			return f:read("*l"):gsub("\n",""):gsub("\r","")
		end)
		if not success or line == nil then
			f:close()
			line = nil
		end
		return line
	end
	
	return iterator, f, ""
end

function GuiLoadSettings()
  for line in io.lines("config.cfg") do
    print(line)
  end
end

GuiLoadSettings()

while true do
  print("hello world")
  emu.frameadvance()
 
end
```

**Comment by mugg91** [comment]
Thank you, this works nicely. As a FYI, it will crash if the cfg file is missing but I adjusted my code and it works now with and without cfg file.

`function doLine(filename)
	local f = io.open(filename, "r")

	local iterator = function(f, prevLine)
		if f==nil then
			return nil
		else
			local success, line = pcall(function()
				return f:read("*l"):gsub("\n",""):gsub("\r","")
			end)
			if not success or line == nil then
				f:close()
				line = nil
			end

			return line
		end
	end

	return iterator, f, ""
end`

**Comment by zeromus** [comment]
config > customize > advanced > lua+luainterface
kopilua's file IO is hopefully screwed. we need to remove it.
but we need you to use lua+luainterface without file IO workarounds first a bunch to confirm that the crashes are fixed.

**Comment by vadosnaprimer** [comment]
Don't remove kopilua just yet, @FelipeLopes might need it.

**Comment by CasualPokePlayer** [comment]
KopiLua was removed in https://github.com/TASEmulators/BizHawk/commit/45fbdb4844b7aefd36e05fd61e99497e566e76bf, KeraLua works fine here.
